### ISSUE TITLE
Windows - Notification of new Stable version, but it's the same as current

### ISSUE THREAD

**Issue by IdiosApps** [LizardByte/Sunshine#1387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

![image](https://github.com/LizardByte/Sunshine/assets/12559216/029f7962-ab61-426c-8108-c2ca2d46b808)

I installed the latest Windows version from GitHub earlier.

Looking at the code, this v-if is triggering:
- https://github.com/LizardByte/Sunshine/blob/31e8b798dabf47d5847a1b485f57cf850a15fcae/src_assets/common/assets/web/index.html#L30
- https://github.com/LizardByte/Sunshine/blob/31e8b798dabf47d5847a1b485f57cf850a15fcae/src_assets/common/assets/web/index.html#L103

https://localhost:47990/api/config
```json
{
    "status": "true",
    "platform": "windows",
    "version": "0.20.0"
}
```

https://api.github.com/repos/LizardByte/Sunshine/releases/latest
```json
{
  ...
  "name": "v0.20.0",
  ...
}
```

Bearing this in mind with the code, it seems to be doing:

```
      stableBuildAvailable() {
        // have githubVersion (with name: v0.20.0), and version /api/config 0.20.0 - so, continue
        if (!this.githubVersion || !this.version) return false; 

        // Get the GitHub version tag
        let v = this.githubVersion.name; // v0.20.0
        // If the version starts with a v, remove it
        if (v.indexOf("v") === 0) v = v.substring(1); // 0.20.0

        // 0.20.0
        // .split(".") : ["0", "20", "0"]
        // [0]         :  "0"
        // check 0.20.2 !== 0?
        return v !== this.version.split(".")[0];
      },
```

I would guess we can remove the splitting and getting the 0th element? 
GitHub version, remove v = "0.20.2"
/api/config version = "0.20.2"

### Expected Behavior

If I'm on latest stable, don't give render this CTA

### Host Operating System

Windows

### Operating System Version

11

### Architecture

64 bit

### Sunshine commit or version

0.20.2

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

 3080

### GPU Driver/Mesa Version

n/a

### Config

```Shell
n/a
```

### Relevant log output

```shell
logs disabled
```

**Comment by ReenigneArcher** [comment]
This was already fixed in nightly.

**Comment by IdiosApps** [comment]
Oh my bad, I checked the master branch (which I assumed nightly is built from) and this code looked the same (https://github.com/LizardByte/Sunshine/blob/master/src_assets/common/assets/web/index.html#L103-L119).

**Comment by burner1024** [comment]
This is not fixed. Please reopen.
![Screenshot from 2023-11-19 01-28-39](https://github.com/LizardByte/Sunshine/assets/1279852/62b08340-79f7-4824-b07d-59bf170cbcad)

**Comment by ReenigneArcher** [comment]
@burner1024 which package are you using from our GitHub releases?

**Comment by burner1024** [comment]
ubuntu 22.04 amd64 deb
