### ISSUE TITLE
"nprotect game guard" blocks keyboard and mouse when enabled

### ISSUE THREAD

**Issue by phoenix91love** [LizardByte/Sunshine#1416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

Connect moonlight to sunshine, when "nprotect game guard" is run by another software, can't move mouse, keyboard

### Host Operating System

Windows

### Operating System Version

Windows 10

### Architecture

64 bit

### Sunshine commit or version

2.0

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

Rtx 1080 ti

### GPU Driver/Mesa Version

497.29 and latest

### Config

```Shell
gamepad = ds4
origin_pin_allowed = wan
origin_web_ui_allowed = wan
```

### Relevant log output

```shell
.
```

**Comment by Kellaim** [comment]
all anticheats block any input from client, in moonlight this`s problem was solved few years ago

**Comment by phoenix91love** [comment]
How to fix input blocking sunshine- moonlight when "nprotect game guard" is open

**Comment by Kellaim** [comment]
[phoenix91love](https://github.com/phoenix91love) now - u can`t do it, only sunshine developers resolve this issue

**Comment by phoenix91love** [comment]
I hope the development team can solve this problem soon. Because there are a lot of games using it right now

**Comment by ns6089** [comment]
Quite frankly, there's not much to solve since both sides are working as intended. Nprotect wants to block all manner of emulated input in their crusade against bots, sunshine can only produce emulated input since it's lacking physical devices. We can play the game of cat and mouse and masquerade as something we're not, but all it's gonna take for nprotect is to mark our driver as malicious and refuse to launch altogether.

**Comment by TsaiTung-Chen** [comment]
I've tried streaming using NVIDIA GameStream + moonlight and Microsoft Remote Desktop. My keyboard input won't be blocked.

It's a shame that Sunshine works great but don't support these games with anti-cheat.

**Comment by ReenigneArcher** [comment]
> It's a shame that Sunshine works great but does not support these games with anti-cheat.

It's a shame that anti-cheats don't really do anything to detect real cheaters. Just block stupid things like running in a VM, Linux users, and virtual gamepads... and call it a day.

**Comment by FurqanM** [comment]
@cgutman If Moonlight, Remote play, and NVIDIA Geforce, Shield, and these devices aren't working because of emuluted input, I've seen reports that say Parsec works, why is that? And can anything be done to do it similarly to Parsec so it does work?

**Comment by Acru** [comment]
> > It's a shame that Sunshine works great but does not support these games with anti-cheat.
> 
> It's a shame that anti-cheats don't really do anything to detect real cheaters. Just block stupid things like running in a VM, Linux users, and virtual gamepads... and call it a day.

Apparently INCA Internet, the makers of Gameguard, are aware of the issue and wish to fix it.

Someone on the Helldivers 2 discord shared this reply to a support request just the other day;

![BH30lap](https://github.com/LizardByte/Sunshine/assets/626242/5539af6b-6a12-4ac9-b542-eecde3065bc7)

Perhaps a fix is possible if Sunshine devs reach out to them or vice versa?

**Comment by Acru** [comment]
There was an update to gameguard that fixed sunshine compatibility for helldivers 2, though I have no idea about the other games it is used in

**Comment by markusbrand** [comment]
I'm still having the issue with my mouse input for steering my Helldiver. The keyboard inputs work and also the mouse works in the menus. But I can't look around, aim .... Usually after some time in the game it starts working again, but still very annoying.

**Comment by markusbrand** [comment]
> There was an update to gameguard that fixed sunshine compatibility for helldivers 2, though I have no idea about the other games it is used in

whatever they fixed - mouse is still not working.

**Comment by Acru** [comment]
> > There was an update to gameguard that fixed sunshine compatibility for helldivers 2, though I have no idea about the other games it is used in
> 
> whatever they fixed - mouse is still not working.

It is working now for everyone else that was using sunshine, on the helldiver's discord.  The specific issue discussed here, where gamegaurd explicitly blocked _all_ virtual keyboard and mouse input was fixed (for helldivers 2 at least), so your issue must be something else.

**Comment by egrechko** [comment]
> > > There was an update to gameguard that fixed sunshine compatibility for helldivers 2, though I have no idea about the other games it is used in
> > 
> > 
> > whatever they fixed - mouse is still not working.
> 
> It is working now for everyone else that was using sunshine, on the helldiver's discord. The specific issue discussed here, where gamegaurd explicitly blocked _all_ virtual keyboard and mouse input was fixed (for helldivers 2 at least), so your issue must be something else.

IDK what you're talking about but it most definitely is not fixed. Helldivers 2 is the only game that doesn't register my mouse. Logitech Pro Wireless doesn't work wireless or wired.

**Comment by Acru** [comment]
> IDK what you're talking about but it most definitely is not fixed. Helldivers 2 is the only game that doesn't register my mouse. Logitech Pro Wireless doesn't work wireless or wired.

Try the helldivers 2 discord for help, every post I saw there said Sunshine-specific issues were resolved by the Feb 27th gameguard update, so if you are still having issues you should look help there, not here, or else file a ticket with arrowhead/nprotect.

I will give you a few more suggestions, but I will stop watching this thread and won't reply again. What mouse you have should make no difference as gameguard was reacting to sunshine's virtual mouse device.  You might try running the gameguard uninstaller included in the game's install folder, to make it update fresh.  You might check that sunshine is up to date too, along with its virtual devices, and check what other virtual/real devices are connected to the host machine.  I did see a post about gameguard reacting when a particular brand of usb microphone was connected, for instance, which happened whether or not sunshine was used.  Again, if none of this helps, try the helldivers 2 discord.

**Comment by markusbrand** [comment]
uninstall didn't help - but when I changed to proton 8.0.4 it worked again - but it seems to be randomly - at least I can't identify any pattern - it's gambling after every update. I checked on helldiver 2 Discord as proposed, but I found immediately two persons who are having the same issue - so @Acru I'm sorry but I can't agree.
