### ISSUE TITLE
 All powershell command preps fail even after PR #2125

### ISSUE THREAD

**Issue by Mothamoz** [LizardByte/Sunshine#2128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

For the previous issue: https://github.com/LizardByte/Sunshine/issues/2121

Supposedly fixed in PR #2125 

Streams still fail because it's not able to run the Powershell prep commands, this time with a different Powershell error 196608

See log output below

### Host Operating System

Windows

### Operating System Version

Windows 11 Pro 22H2 22621.3007

### Architecture

64 bit

### Sunshine commit or version

0.21.0.78ed91af5cf56bd0e0195c66048064876e285761

### Package

Windows - installer

### GPU Type

Nvidia

### GPU Model

RTX 4070Ti

### GPU Driver/Mesa Version

551.46

### Config

```Shell
av1_mode = 3
encoder = nvenc
hevc_mode = 3
global_prep_cmd = [{"do":"powershell.exe -executionpolicy bypass -windowstyle hidden -file \"D:\\Program Files\\PlayNite Scripts\\AutoStartApps.ps1\"","undo":"powershell.exe -executionpolicy bypass -windowstyle hidden -file \"D:\\Program Files\\PlayNite Scripts\\AutoStopApps.ps1\"","elevated":"true"},{"do":"","undo":"powershell.exe -executionpolicy bypass -windowstyle hidden -file \"C:\\Program Files (x86)\\PlayNiteWatcher\\PlayNiteWatcher-EndScript.ps1\" True","elevated":false},{"do":"powershell.exe -executionpolicy bypass -WindowStyle Hidden -file \"D:\\Program Files (x86)\\ResolutionMatcher\\ResolutionMatcher.ps1\"","undo":"powershell.exe -executionpolicy bypass -WindowStyle Hidden -file \"D:\\Program Files (x86)\\ResolutionMatcher\\ResolutionMatcher-Functions.ps1\" True","elevated":false},{"do":"powershell.exe -executionpolicy bypass -file \"D:\\Program Files (x86)\\AutoMonitorSwap\\MonitorSwapper.ps1\"","undo":"powershell.exe -executionpolicy bypass -file \"D:\\Program Files (x86)\\AutoMonitorSwap\\MonitorSwapper-Functions.ps1\" True","elevated":false}]
origin_pin_allowed = lan
sunshine_name = Sunshine
resolutions = [
    2560x1440,
    3860x2160
]
upnp = enabled
min_log_level = 1
```

### Relevant log output

```shell
[2024:02:10:20:11:09]: Debug: Parsed target [powershell.exe] from command [powershell.exe -executionpolicy bypass -WindowStyle Hidden -file "D:\Program Files (x86)\ResolutionMatcher\ResolutionMatcher.ps1"]
[2024:02:10:20:11:09]: Debug: Resolved target [powershell.exe] to path ["c:\windows\system32\windowspowershell\v1.0\powershell.exe"]
[2024:02:10:20:11:09]: Info: Executing Do Cmd: [powershell.exe -executionpolicy bypass -WindowStyle Hidden -file "D:\Program Files (x86)\ResolutionMatcher\ResolutionMatcher.ps1"]
[2024:02:10:20:11:09]: Info: Resolved user-provided command 'powershell.exe -executionpolicy bypass -WindowStyle Hidden -file "D:\Program Files (x86)\ResolutionMatcher\ResolutionMatcher.ps1"' to '"powershell.exe" -executionpolicy bypass -WindowStyle Hidden -file D:\Program Files (x86)\ResolutionMatcher\ResolutionMatcher.ps1'
[2024:02:10:20:11:09]: Info: powershell.exe -executionpolicy bypass -WindowStyle Hidden -file "D:\Program Files (x86)\ResolutionMatcher\ResolutionMatcher.ps1" running with PID 4684
[2024:02:10:20:11:09]: Error: [powershell.exe -executionpolicy bypass -WindowStyle Hidden -file "D:\Program Files (x86)\ResolutionMatcher\ResolutionMatcher.ps1"] failed with code [-196608]
[2024:02:10:20:11:09]: Debug: Parsed target [powershell.exe] from command [powershell.exe -executionpolicy bypass -windowstyle hidden -file "C:\Program Files (x86)\PlayNiteWatcher\PlayNiteWatcher-EndScript.ps1" True]
[2024:02:10:20:11:09]: Debug: Resolved target [powershell.exe] to path ["c:\windows\system32\windowspowershell\v1.0\powershell.exe"]
[2024:02:10:20:11:09]: Info: Executing Undo Cmd: [powershell.exe -executionpolicy bypass -windowstyle hidden -file "C:\Program Files (x86)\PlayNiteWatcher\PlayNiteWatcher-EndScript.ps1" True]
[2024:02:10:20:11:09]: Info: Resolved user-provided command 'powershell.exe -executionpolicy bypass -windowstyle hidden -file "C:\Program Files (x86)\PlayNiteWatcher\PlayNiteWatcher-EndScript.ps1" True' to '"powershell.exe" -executionpolicy bypass -windowstyle hidden -file C:\Program Files (x86)\PlayNiteWatcher\PlayNiteWatcher-EndScript.ps1 True'
[2024:02:10:20:11:09]: Info: powershell.exe -executionpolicy bypass -windowstyle hidden -file "C:\Program Files (x86)\PlayNiteWatcher\PlayNiteWatcher-EndScript.ps1" True running with PID 3104
[2024:02:10:20:11:09]: Warning: Return code [-196608]
```

**Comment by ReenigneArcher** [comment]
The issue appears to be that the quotes were removed from the path.

**Comment by cgutman** [comment]
Yeah, unfortunately Boost's argument parser is stripping them out. I'll prepare another PR...

**Comment by cgutman** [comment]
@Mothamoz you can try the build from #2129 and confirm it fixes the issue: https://github.com/LizardByte/Sunshine/actions/runs/7857563497/artifacts/1235854618

**Comment by Mothamoz** [comment]
> @Mothamoz you can try the build from #2129 and confirm it fixes the issue: https://github.com/LizardByte/Sunshine/actions/runs/7857563497/artifacts/1235854618

Fixed in this build!

**Comment by romracer** [comment]
This still doesn't work for me.  Here's my app config that works fine on 0.21.0:

```
        {
            "name": "GS Playnite 1080p",
            "cmd": "Playnite.FullscreenApp.exe",
            "working-dir": "D:\\Apps\\Playnite",
            "image-path": "C:\\Users\\romracer\\Pictures\\Sunshine\\GS Playnite.png",
            "prep-cmd": [
                {
                    "do": "D:\\Apps\\Sunshine\\QRes.exe /X:1920 /Y:1080 /C:32 /R:120",
                    "undo": "D:\\Apps\\Sunshine\\QRes.exe /X:1920 /Y:1080 /C:32 /R:60"
                },
				{
					"do": "C:\\Windows\\System32\\cmd.exe /C \"start /b /d \"C:\\Program Files (x86)\\VB\\Voicemeeter\\\" voicemeeter.exe\"",
					"undo": "C:\\Windows\\System32\\taskkill.exe /im voicemeeter.exe"
				}
            ],
            "detached": [
                "D:\\Apps\\Sunshine\\GameStreamFixMouse_V1.4.exe"
            ]
        },
```

And the relevant log lines:

```
[2024:02:11:11:33:28]: Info: Executing Do Cmd: [C:\Windows\System32\cmd.exe /C "start /b /d "C:\Program Files (x86)\VB\Voicemeeter\" voicemeeter.exe"]
[2024:02:11:11:33:28]: Info: Resolved user-provided command 'C:\Windows\System32\cmd.exe /C "start /b /d "C:\Program Files (x86)\VB\Voicemeeter\" voicemeeter.exe"' to '"C:\Windows\System32\cmd.exe" /C "start /b /d C:\Program" Files "(x86)\VB\Voicemeeter\"" voicemeeter.exe'
[2024:02:11:11:33:28]: Info: C:\Windows\System32\cmd.exe /C "start /b /d "C:\Program Files (x86)\VB\Voicemeeter\" voicemeeter.exe" running with PID 18060
[2024:02:11:11:33:29]: Error: [C:\Windows\System32\cmd.exe /C "start /b /d "C:\Program Files (x86)\VB\Voicemeeter\" voicemeeter.exe"] failed with code [1]
```

Looking at my do cmd, it seems I'm using lots of " quotes, but it works fine in 0.21.0.

**Comment by ReenigneArcher** [comment]
@romracer what doesn't work for you? Nightly?

**Comment by romracer** [comment]
The artifact from the linked PR. Sorry that wasn't more clear.

**Comment by ReenigneArcher** [comment]
I'm not arguing that there aren't issues with the command parsing, but ...

Your command is unnecessarily complicated.

`cmd /C` is not needed unless you are using `start` (or other shell commands)... which you are... but you don't need to if you are running an `.exe`

Your command can simply be the full path to your exe file. This is likely the fault of the examples in the docs.

**Comment by romracer** [comment]
@ReenigneArcher what would be the equivalent of setting the working directory (`/d`) in that scenario (calling the exe directly).  If I remember right, it's that which caused me to use `start`.  voicemeeter in this case requires it.

**Comment by ReenigneArcher** [comment]
Set the working directory field in the apps config page.

**Comment by romracer** [comment]
But I have that set to the directory of the actual app I'm running.

**Comment by ReenigneArcher** [comment]
No... you put the full path to the command in the command field.

**Comment by ReenigneArcher** [comment]
Although... I kind of doubt `voicemeeter.exe` requires the working directory to be the directory where the exe is located.

**Comment by cgutman** [comment]
@romracer The issue with your command is that you fail to escape the quotes inside your command. This is why that quote before the working directory is interpreted as a matching end quote and you end up with `"start /b /d "` as the quoted string. 

Adding a couple of `\` to properly escape those internal quotes according to [the Windows command-line parsing rules](https://learn.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments?view=msvc-170) fixes it.

`C:\Windows\System32\cmd.exe /C "start /b /d "C:\Program Files (x86)\VB\Voicemeeter\" voicemeeter.exe"` ->

`C:\Windows\System32\cmd.exe /C "start /b /d \"C:\Program Files (x86)\VB\Voicemeeter\\" voicemeeter.exe"`

However, because changing command escaping rules is a breaking change, I'm going to ensure that explicitly specified exe files get the old behavior to avoid regressing existing configs.
