### ISSUE TITLE
Screen Tearing/VSync Issue in KDE Plasma Wayland, Gnome Wayland

### ISSUE THREAD

**Issue by neatnoise** [LizardByte/Sunshine#3189]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Even with VSync enabled both in KDE desktop environment settings and individual game settings, screen tearing still occurs in most games that I have. I am running the latest version of Arch Linux with KDE Plasma Wayland (ver 6.1.5) installed. I primarily experience the issue in games through DXVK. Some games handle VSync correctly, while others consistently show tearing (e.g., Amnesia The Bunker, The Witcher, Mafia: Definitive Edition). It is a quite aggressive tearing, after a while it is tiring for the eyes.

This issue occurs across devices when using the Moonlight client (MacOS, iOS), but is not a client problem as the same problem is noticeable on different client systems. Games run correctly on a physically connected monitor with VSync enabled, but tearing appears when using the Moonlight client, even though VSync is also enabled in the client. I use the latest Moonlight (ver 6.0.1) for MacOS (11.7).

EDIT: Gnome 46 Wayland (Arch linux) also has the same issue. So it could be Wayland desktops related.

I recorded a short video showing the issue https://www.youtube.com/watch?v=4bVXx2cKRP8

Steps to Reproduce:

- Enable VSync in KDE Plasma Wayland settings.
- Run any game (preferably these with DXVK) and ensure VSync is enabled in the game’s settings.
- Stream the game via the Moonlight client.
- Observe the screen tearing issue.

### Expected Behavior

No tearing with vsync on.

### Host Operating System

Linux

### Operating System Version

Latest Arch Linux

### Architecture

64 bit

### Sunshine commit or version

Latest git master

### Package

Linux - AUR (Third Party)

### GPU Type

AMD

### GPU Model

AMD Radeon RX 580

### GPU Driver/Mesa Version

Mesa 24.2.2

### Capture Method

wlroots (Linux)

### Config

```Shell
channels = 3
nv_rc = auto
address_family = both
resolutions = [
    1280x720,
    1920x1080
]
encoder = vaapi
file_state = 
fps = [60]
upnp = enabled
nv_preset = default
lan_encryption_mode = 2
wan_encryption_mode = 2
external_ip = 
cert = 
pkey =
```

### Relevant log output

```shell
Sep 06 18:21:37 tm-stc sunshine[1202]: Warning: Unrecognized configurable option [nv_rc]
Sep 06 18:21:37 tm-stc sunshine[1202]: Warning: Unrecognized configurable option [resolutions]
Sep 06 18:21:37 tm-stc sunshine[1202]: Warning: Unrecognized configurable option [fps]
Sep 06 18:21:37 tm-stc sunshine[1202]: Warning: Unrecognized configurable option [nv_preset]
Sep 06 18:21:37 tm-stc sunshine[1202]: [2024-09-06 18:21:37.155]: Info: Sunshine version: 0.0.0.dirty
Sep 06 18:21:37 tm-stc sunshine[1202]: [2024-09-06 18:21:37.156]: Info: Package Publisher: Third Party Publisher
Sep 06 18:21:37 tm-stc sunshine[1202]: [2024-09-06 18:21:37.156]: Info: Publisher Website:
Sep 06 18:21:37 tm-stc sunshine[1202]: [2024-09-06 18:21:37.156]: Info: Get support: https://app.lizardbyte.dev/support
Sep 06 18:21:37 tm-stc sunshine[1202]: [2024-09-06 18:21:37.195]: Info: Found display [wayland-0]
Sep 06 18:21:37 tm-stc sunshine[1202]: [2024-09-06 18:21:37.195]: Info: Found interface: zxdg_output_manager_v1(31) version 3
...skipping...
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.904]: Info: CLIENT CONNECTED
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.907]: Info: /dev/dri/card1 -> amdgpu
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Found display [wayland-0]
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Found interface: zxdg_output_manager_v1(31) version 3
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Found interface: wl_output(63) version 4
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Resolution: 1920x1080
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Offset: 0x0
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Logical size: 1280x720
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Name: HDMI-A-2
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Found monitor: Philips Consumer Electronics Company Philips FTV/0x01010101
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: -------- Start of KMS monitor list --------
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Monitor 0 is HDMI-A-2: Philips Consumer Electronics Company Philips FTV/0x01010101
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: --------- End of KMS monitor list ---------
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.908]: Info: Screencasting with KMS
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.909]: Info: /dev/dri/card1 -> amdgpu
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.909]: Info: Found monitor for DRM screencasting
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.909]: Info: Found connector ID [95]
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.909]: Info: Found cursor plane [61]
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.935]: Info: Creating encoder [h264_vaapi]
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.935]: Info: Color coding: SDR (Rec. 601)
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.935]: Info: Color depth: 8-bit
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.935]: Info: Color range: MPEG
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.985]: Info: vaapi vendor: Mesa Gallium driver 24.2.2-arch1.1 for AMD Radeon RX 580 Series (rade>
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.988]: Error: [h264_vaapi @ 0x711c60508e00] No usable encoding entrypoint found for profile VAPr>
Sep 16 00:21:39 tm-stc sunshine[13427]: [2024-09-16 00:21:39.990]: Info: Retrying with fallback configuration options for [h264_vaapi] after error: Function>
Sep 16 00:21:40 tm-stc sunshine[13427]: [2024-09-16 00:21:40.012]: Info: vaapi vendor: Mesa Gallium driver 24.2.2-arch1.1 for AMD Radeon RX 580 Series (rade>
Sep 16 00:21:40 tm-stc sunshine[13427]: [2024-09-16 00:21:40.016]: Warning: [h264_vaapi @ 0x711c6023da40] Driver does not support some wanted packed headers>
Sep 16 00:21:40 tm-stc sunshine[13427]: [2024-09-16 00:21:40.410]: Info: Found default monitor by name: alsa_output.pci-0000_00_14.2.iec958-stereo.monitor
Sep 16 00:21:40 tm-stc sunshine[13427]: [2024-09-16 00:21:40.446]: Info: Opus initialized: 48 kHz, 2 channels, 512 kbps (total), LOWDELAY
```

**Comment by DistantThunder** [comment]
Glad to know I'm not the only one:

* https://github.com/LizardByte/Sunshine/discussions/3089

**Comment by DistantThunder** [comment]
Could this be it?

* https://gitlab.freedesktop.org/mesa/mesa/-/issues/11913

It says here the issue existed for years but this seems to have appeared just a few months ago.

**Comment by neatnoise** [comment]
It could be. I'm doing the research too, testing different desktop environments, settings within envs, forcing different driver settings. No success so far. The issue doesn't exist on the physical screen so it might be indeed vaapi, ffmpeg thing.

**Comment by neatnoise** [comment]
@DistantThunder great spot. That's the root cause - ffmpeg synchronization during encoding. I compiled the ffmpeg code with the first patch provided in the mesa thread and it fixes tearing issue. They mention that it is a workaround and not real fix, but it does the thing for now so I will use it till the real fix is provided in ffmpeg code. I'm sharing the Linux-x86_64 compiled ffmpeg with the patch that can be used with Sunshine compilation (Sunshine/third-party/build-deps/ffmpeg/Linux-x86_64)
[ffmpeg_build.zip](https://github.com/user-attachments/files/17090098/ffmpeg_build.zip)

**Comment by ReenigneArcher** [comment]
@neatnoise could you submit a PR with the patch to https://github.com/LizardByte/build-deps

**Comment by neatnoise** [comment]
> @neatnoise could you submit a PR with the patch to https://github.com/LizardByte/build-deps

Added [FFmpeg Vulkan synchronization fix](https://github.com/LizardByte/build-deps/pull/357). Worth to mention that it is a workaround and should be monitored and removed when the real fix is provided in FFmpeg project

**Comment by DistantThunder** [comment]
@neatnoise Nice! Did you patch your system's ffmpeg?

**Comment by neatnoise** [comment]
@DistantThunder Sunshine uses its own built static FFmpeg library, not system's one. It is here https://github.com/LizardByte/build-deps

**Comment by DistantThunder** [comment]
@neatnoise even when building locally (I'm using Git).

**Comment by DistantThunder** [comment]
Ah yes, thanks for the help, I could do this like this on Arch with the Sunshine PKGBUILD :

* git+https://github.com/LizardByte/build-deps.git#commit='d9a9e0edd3bfefa604958339eca2db642683ebcf'

**Comment by ReenigneArcher** [comment]
No, it's not compiled yet.

**Comment by DistantThunder** [comment]
> No, it's not compiled yet.

Sorry, I meant I compiled my own build with the patch.

**Comment by ReenigneArcher** [comment]
You can't use any git commit for build-deps in a PKGBUILD because the patch hasn't been compiled into the `dist` branch yet. This is where the submodule points to: https://github.com/LizardByte/build-deps/tree/dist

**Comment by DistantThunder** [comment]
@ReenigneArcher I eventually made my own build:

https://github.com/DistantThunder/sunshine-build-deps/actions/runs/11020194305/job/30604435143

It makes things noticeably better but the tearing persists.

**Comment by ReenigneArcher** [comment]
Thanks for the update

**Comment by DistantThunder** [comment]
I restarted my machine and upgraded to Mesa 24.2.3. I could no longer see the tearing with the same Sunshine build but I had stutters in heavy action scenes with the scene sometimes clipping. Getting closer it seems.

**Comment by neatnoise** [comment]
@DistantThunder try to use the latest ffmpeg dev code. There is a proper fix already in master ffmpeg branch. It works the best for me.

Change in file https://github.com/LizardByte/build-deps/blob/master/.gitmodules
```
[submodule "ffmpeg_sources/ffmpeg"]
	path = ffmpeg_sources/ffmpeg
	url = https://github.com/FFmpeg/FFmpeg
	branch = master
```
reinit git submodules and compile build-deps

**Comment by DistantThunder** [comment]
@neatnoise Will test. I was afraid Sunshine bindings were not compatible with upstream latest.

**Comment by neatnoise** [comment]
> @neatnoise Will test. I was afraid Sunshine bindings were not compatible with upstream latest. So I have to remove the patches?

Yes, I built without any patches and works fine

**Comment by DistantThunder** [comment]
@neatnoise Current master looks broken:
* https://github.com/DistantThunder/sunshine-build-deps/actions/runs/11075266714/job/30775832935

I had to correct cbs imports as well (https://github.com/DistantThunder/sunshine-build-deps/commit/f4d417c7b993a4a7478827c2c9418a848eceb1be)

What commit did you use?

**Comment by neatnoise** [comment]
https://github.com/FFmpeg/FFmpeg/commit/a577d313b2c14c855ab8aa69bbe3527bd7727212 This one. I didn’t have to change anything to build it

**Comment by DistantThunder** [comment]
Ok, I don't know then

```
                 from /tmp/makepkg/sunshine-git/src/Sunshine/src/cbs.cpp:6:
/tmp/makepkg/sunshine-git/src/Sunshine/third-party/build-deps/ffmpeg/Linux-x86_64/include/cbs/x86/mathops.h:25:10: fatal error: config.h: No such file or directory
   25 | #include "config.h"
      |          ^~~~~~~~~~
compilation terminated.

```
I can't compile Sunshine using the dist build with that ffmpeg commit.

**Comment by ReenigneArcher** [comment]
Our "dist" build is pre compiled. We haven't compiled that commit into it. You have to compile ffmpeg yourself, as we do in build-deps, then replace the submodule with your precompiled version.

**Comment by neatnoise** [comment]
I use act to simulate github workflow with modified build-ffmpeg.yml a bit:

- removed --enable-cuda_llvm switch in ffmpeg extra options
- removed all other architecture entries with leaving only Linux-x86_64
- removed ffmpeg patching step
- pointed branch = master in .gitmodules ffmpeg
Then I enter using bash in the docker container, copy all build outputs to sunshine tree
In the end I run AUR aur/sunshine-git installation  with custom script added to replace original build-deps outputs with my compiled ones

```
cd third-party/build-deps/ffmpeg
wget https://<url>.zip
unzip ffmpeg_build_dev.zip
rm ffmpeg_build_dev.zip
rm -rf Linux-x86_64
mv ffmpeg_build Linux-x86_64
cd ../../../
```

**Comment by DistantThunder** [comment]
@neatnoise  Can you zip link your ffmpeg  build-deps outputs? I suspect your "copy all build outputs for sunshine tree" may be the key here.

**Comment by neatnoise** [comment]
This is https://github.com/FFmpeg/FFmpeg/commit/a577d313b2c14c855ab8aa69bbe3527bd7727212 commit build 
[ffmpeg_build_dev.zip](https://github.com/user-attachments/files/17196505/ffmpeg_build_dev.zip)

**Comment by DistantThunder** [comment]
Thank you!

**Comment by ReenigneArcher** [comment]
We're working on updating ffmpeg to 7.1, which will properly fix this. https://github.com/LizardByte/build-deps/pull/359

**Comment by DistantThunder** [comment]
Yes, I just made a build using cgutman repo as a remote and the build worked with latest master this time.
The tearing is gone, now is just the old issue of the stream becoming stutter-y and clip-pey whenever I'm not at 60 fps.

**Comment by neatnoise** [comment]
I have similar conclusions. Tearing is fixed, but there is kind of stuttering. The feeling is similar like network lags in games, it backs off and forward a bit when the character is moved. Probably also ffmpeg causes it.

**Comment by neatnoise** [comment]
I recorded a video displaying the stuttering issue. Looks like the frames are not displayed in order, or in the right time (delayed). It adds latency unfortunately, it is hard to react for the user in fast games and tiring for the eyes. No screen tearing. The issue is specially visible when the frames are generated close to 60 fps (45-59 fps) with 60 hz monitor. [https://www.youtube.com/watch?v=D8LE-SqZV6w](url)

**Comment by ReenigneArcher** [comment]
Those still experiencing stuttering, do you have VSync enabled or disabled? If enabled, can you try disabling it and report back?

**Comment by 5685C4A059D5** [comment]
Do you mean in the game? I get tearing with both vsync on and off.

**Comment by neatnoise** [comment]
I experience stuttering with latest master of sunshine. There is no tearing with vsync on for me.

**Comment by Trasen** [comment]
Experiencing this exact issue on latest Bazzite. The comment previously about "frames are not outputted in order" rings.

Locking in-game fps to 30 on a 60 or 120fps capture makes it more obvious, almost looks like the captured frames loop over each other on the client.

Is it possible that instead of dropping off-frames the capture re-use 3-4 frames until sync has been achived?

**Comment by badjware** [comment]
I managed to almost completely mitigate the issue by uncapping the framerate, disabling vsync, and enabling frame gen. At around 180 fps the issue become almost imperceptible.

**Comment by aresbigboy** [comment]
Under the same conditions, there is no screen tearing issue with Steam Link.

**Comment by neatnoise** [comment]
The issue still exists in sunshine master branch
