### ISSUE TITLE
Systray icon appears blank when using Sunshine AppImage

### ISSUE THREAD

**Issue by sabre230** [LizardByte/Sunshine#3329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

Anytime I use the Sunshine appimage, the tray icon does not appear. It has been present in the last few pre-release builds.

### Expected Behavior

When starting the Sunshine appimage, the Sunshine systray icon should appear.

### Additional Context

> Example
![example](https://github.com/user-attachments/assets/4c3c7d6e-bd0f-440c-b724-853890773698)

> Software:
`Linux 
PASADENA 
6.8.0-47-generic 
#47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 
x86_64
GNU/Linux`

> Graphics:
`01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1)
        Subsystem: eVga.com. Corp. GP104 [GeForce GTX 1080] [3842:6685]
--
10:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raphael [1002:164e] (rev c3)
        Subsystem: Micro-Star International Co., Ltd. [MSI] Raphael [1462:7e26]`

### Host Operating System

Linux

### Operating System Version

Kubuntu 24.04 (KDE Plasma: 5.27.11, KDE Frameworks: 5.115.0, Qt: 5.15.13))

### Architecture

amd64/x86_64

### Sunshine commit or version

v2024.1021.153031

### Package

Linux - AppImage

### GPU Type

Nvidia

### GPU Model

EVGA GeForce 1080 ACX 3.0 8GB

### GPU Driver/Mesa Version

Nvidia Driver: 560.35.03, NVML Version: 12.560.35.03

### Capture Method

X11 (Linux)

### Config

```Shell
global_prep_cmd = [{"do":"xrandr --output DP-0 --mode 1920x1080 --refresh 60","undo":"xrandr --output DP-0 --mode 3840x1200 --refresh 120"},{"do":"qdbus org.kde.KWin /Compositor suspend","undo":"qdbus org.kde.KWin /Compositor resume"},{"do":"rfkill block bluetooth","undo":"rfkill unblock bluetooth"},{"do":"openrgb -p \"All Off\"","undo":"openrgb -p \"Pink\""},{"do":"pkill openrgb","undo":""}]
```

### Relevant log output

```shell
[global_prep_cmd] -- [[{"do":"xrandr --output DP-0 --mode 1920x1080 --refresh 60","undo":"xrandr --output DP-0 --mode 3840x1200 --refresh 120"},{"do":"qdbus org.kde.KWin /Compositor suspend","undo":"qdbus org.kde.KWin /Compositor resume"},{"do":"rfkill block bluetooth","undo":"rfkill unblock bluetooth"},{"do":"openrgb -p \"All Off\"","undo":"openrgb -p \"Pink\""},{"do":"pkill openrgb","undo":""}]]
[2024-10-25 15:19:05.096]: Info: Sunshine version: v2024.1021.153031
[2024-10-25 15:19:05.096]: Info: Package Publisher: LizardByte
[2024-10-25 15:19:05.096]: Info: Publisher Website: https://app.lizardbyte.dev
[2024-10-25 15:19:05.096]: Info: Get support: https://app.lizardbyte.dev/support
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Gtk-Message: 15:19:05.171: Failed to load module "colorreload-gtk-module"
Gtk-Message: 15:19:05.171: Failed to load module "window-decorations-gtk-module"
[2024-10-25 15:19:05.177]: Info: System tray created
[2024-10-25 15:19:05.327]: Info: Found [1] outputs
[2024-10-25 15:19:05.327]: Info: Virtual Desktop: 1920x1080
[2024-10-25 15:19:05.327]: Info: XrandR: available
[2024-10-25 15:19:05.327]: Info: -- Output --
[2024-10-25 15:19:05.327]: Info:   Resolution: 1920x1080
[2024-10-25 15:19:05.327]: Info:   Offset: 0x0
[2024-10-25 15:19:05.343]: Error: Couldn't release NvFBC context from current thread: 
[2024-10-25 15:19:05.343]: Info: Detecting displays
```

**Comment by ReenigneArcher** [comment]
> /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Gtk-Message: 15:19:05.171: Failed to load module "colorreload-gtk-module"
Gtk-Message: 15:19:05.171: Failed to load module "window-decorations-gtk-module"

I suppose it's due to this. Can you try the very latest beta release?

**Comment by sabre230** [comment]
I noticed that after I shared the issue, that's my b. I updated but it appears the issue persists. 

`sabre230@PASADENA:~/Applications/Moonlight$ ./sunshine.AppImage
[global_prep_cmd] -- [[{"do":"xrandr --output DP-0 --mode 1920x1080 --refresh 60","undo":"xrandr --output DP-0 --mode 3840x1200 --refresh 120"},{"do":"qdbus org.kde.KWin /Compositor suspend","undo":"qdbus org.kde.KWin /Compositor resume"},{"do":"rfkill block bluetooth","undo":"rfkill unblock bluetooth"},{"do":"openrgb -p \"All Off\"","undo":"openrgb -p \"Pink\""},{"do":"pkill openrgb","undo":""}]]
[2024-10-25 16:17:03.357]: Info: Sunshine version: v2024.1025.12635
[2024-10-25 16:17:03.357]: Info: Package Publisher: LizardByte
[2024-10-25 16:17:03.357]: Info: Publisher Website: https://app.lizardbyte.dev
[2024-10-25 16:17:03.357]: Info: Get support: https://app.lizardbyte.dev/support
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Gtk-Message: 16:17:03.428: Failed to load module "colorreload-gtk-module"
Gtk-Message: 16:17:03.428: Failed to load module "window-decorations-gtk-module"
[2024-10-25 16:17:03.434]: Info: System tray created
[2024-10-25 16:17:03.566]: Info: Found [1] outputs
[2024-10-25 16:17:03.567]: Info: Virtual Desktop: 1920x1080
[2024-10-25 16:17:03.567]: Info: XrandR: available
[2024-10-25 16:17:03.567]: Info: -- Output --
[2024-10-25 16:17:03.567]: Info:   Resolution: 1920x1080
[2024-10-25 16:17:03.567]: Info:   Offset: 0x0
[2024-10-25 16:17:03.584]: Error: Couldn't release NvFBC context from current thread: 
[2024-10-25 16:17:03.584]: Info: Detecting displays
`

**Comment by ReenigneArcher** [comment]
I think this was probably fixed by https://github.com/LizardByte/Sunshine/pull/3561 (even though the main changes were regarding flatpak)

**Comment by oodzchen** [comment]
This still happened on the latest AppImage (v2025.628.4510) .

OS: openSUSE Tumbleweed
DE: KDE Plasma 6.4.1
