### ISSUE TITLE
Sunshine installation failed

### ISSUE THREAD

**Issue by zh88782** [LizardByte/Sunshine#3387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/open
Last 15 lines from /Users/macos/Library/Logs/Homebrew/sunshine/01.cmake:
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'libcurl'
--   Package 'ldap', required by 'libcurl', not found
CMake Error at /usr/local/opt/cmake/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - libcurl

Call Stack (most recent call first):
  /usr/local/opt/cmake/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  cmake/dependencies/common.cmake:16 (pkg_check_modules)
  CMakeLists.txt:50 (include)

-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues

### Expected Behavior

use
brew tap LizardByte/homebrew
brew install sunshine
perhaps
brew tap LizardByte/homebrew
brew install sunshine-beta
Not even possible
use
mkdir -p ~/ports/multimedia/sunshine
cd ~/ports/multimedia/sunshine
curl -OL  https://github.com/LizardByte/Sunshine/releases/latest/download/Portfile
cd ~/ports
portindex
sudo port install sunshine  
It also indicates installation failure
A few months ago, I successfully installed it once. Recently, due to some reasons, I uninstalled it and wanted to reinstall it. However, I encountered the error mentioned above, which has been bothering me for several days. Can you help me find a solution? Thank you

### Additional Context

==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/open
Last 15 lines from /Users/macos/Library/Logs/Homebrew/sunshine/01.cmake:
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'libcurl'
--   Package 'ldap', required by 'libcurl', not found
CMake Error at /usr/local/opt/cmake/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - libcurl

Call Stack (most recent call first):
  /usr/local/opt/cmake/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  cmake/dependencies/common.cmake:16 (pkg_check_modules)
  CMakeLists.txt:50 (include)

-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues

### Host Operating System

macOS

### Operating System Version

Sonoma

### Architecture

amd64/x86_64

### Sunshine commit or version

0.29.2

### Package

macOS - Homebrew

### GPU Type

AMD

### GPU Model

6600XT

### GPU Driver/Mesa Version

unknown

### Capture Method

None

### Relevant log output

```shell
==> cmake -S . -B build -DBUILD_WERROR=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/open
Last 15 lines from /Users/macos/Library/Logs/Homebrew/sunshine/01.cmake:
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'libcurl'
--   Package 'ldap', required by 'libcurl', not found
CMake Error at /usr/local/opt/cmake/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - libcurl

Call Stack (most recent call first):
  /usr/local/opt/cmake/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  cmake/dependencies/common.cmake:16 (pkg_check_modules)
  CMakeLists.txt:50 (include)


-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues
```

**Comment by ReenigneArcher** [comment]
Duplicate of #3180

**Comment by ReenigneArcher** [comment]
This is also fixed in beta already

**Comment by clownchrys** [comment]
"ldap" related lib-curl problem is fixed in beta,
but "mit-krb5-gssapi" related one is still in error

logs are followings:

```
==> Installing lizardbyte/homebrew/sunshine-beta
==> Building docs: disabled
==> Disabled statically linking Boost libraries
==> cmake -S . -B build -DBUILD_WERROR=ON -DHOMEBREW_ALLOW_FETCHCONTENT=ON -DOPE
Last 15 lines from /Users/chan/Library/Logs/Homebrew/sunshine-beta/01.cmake:
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'libcurl'
--   Package 'mit-krb5-gssapi', required by 'libcurl', not found
CMake Error at /usr/local/Cellar/cmake/3.31.0/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - libcurl

Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.31.0/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  cmake/dependencies/common.cmake:19 (pkg_check_modules)
  CMakeLists.txt:54 (include)


-- Configuring incomplete, errors occurred!

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/lizardbyte/homebrew-homebrew/issues
```

**Comment by zh88782** [comment]
It doesn't solve the problem of repeated installation even after dozens of times

**Comment by zh88782** [comment]
cmake -S . -B build -DBUILD_WERROR=ON -DHOMEBREW_ALLOW_FETCHCONTENT=ON -DOPE
Last 15 lines from /Users/macos/Library/Logs/Homebrew/sunshine-beta/01.cmake:
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Checking for module 'libcurl'
--   Package 'mit-krb5-gssapi', required by 'libcurl', not found
CMake Error at /usr/local/opt/cmake/share/cmake/Modules/FindPkgConfig.cmake:645 (message):
  The following required packages were not found:

   - libcurl

Call Stack (most recent call first):
  /usr/local/opt/cmake/share/cmake/Modules/FindPkgConfig.cmake:873 (_pkg_check_modules_internal)
  cmake/dependencies/common.cmake:19 (pkg_check_modules)
  CMakeLists.txt:54 (include)

**Comment by zh88782** [comment]
sudo rm -rf "$(brew --cache --build-from-source sunshine-beta)"
brew install sunshine-beta
Keep reporting this error

**Comment by ReenigneArcher** [comment]
This issue is a duplicate, and closed. Solutions are listed in the pinned duplicate issue.
