### ISSUE TITLE
Mouse and Keyboard unresponsive through Moonlight (Linux Mint Host)

### ISSUE THREAD

**Issue by patach** [LizardByte/Sunshine#3796]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

Having trouble getting my either my Windows 11 machine or my Linux Steam Deck to control my Linux Mint machine using Sunshine and Moonlight.  Input for Mouse Control and Keyboard are enabled, and systemd-udevd is active on Linux Mint.  A mouse and keyboard are also physically connected to the Linux Mint computer.

Sunshine was installed as a flatpak

Is there something I am missing?

### Host Operating System

Linux

### Operating System Version

Linux Mint - Latest Version

### Architecture

amd64/x86_64

### Sunshine commit or version

Version v2025.122.141614

### Package

Linux - flathub/flatpak

### GPU Type

AMD

### GPU Model

AMD Radeon Graphics (radeonsi, phoenix, LLVM 17.0.6, DRM 3.59, 6.8.0-57-generic)

### GPU Driver/Mesa Version

Mesa Gallium driver 25.0.3

### Capture Method

None

### Config

```Shell

```

### Apps

```json

```

### Relevant log output

```shell
[2025-04-14 09:28:58.533]: Info: CLIENT CONNECTED
[2025-04-14 09:28:58.534]: Info: Detecting displays
[2025-04-14 09:28:58.540]: Info: Detected display: DisplayPort-0 (id: 0)DisplayPort-0 connected: true
[2025-04-14 09:28:58.540]: Info: Detected display: HDMI-A-0 (id: 1)HDMI-A-0 connected: false
[2025-04-14 09:28:58.540]: Info: Detected display: DisplayPort-1 (id: 2)DisplayPort-1 connected: false
[2025-04-14 09:28:58.540]: Info: Detected display: DisplayPort-2 (id: 3)DisplayPort-2 connected: false
[2025-04-14 09:28:58.540]: Info: Detected display: DisplayPort-3 (id: 4)DisplayPort-3 connected: false
[2025-04-14 09:28:58.540]: Info: Detected display: DisplayPort-4 (id: 5)DisplayPort-4 connected: false
[2025-04-14 09:28:58.540]: Info: Detected display: DisplayPort-5 (id: 6)DisplayPort-5 connected: false
[2025-04-14 09:28:58.540]: Info: Screencasting with X11
[2025-04-14 09:28:58.541]: Info: Configuring selected display (0) to stream
[2025-04-14 09:28:58.546]: Info: Streaming display: DisplayPort-0 with res 3840x2160 offset by 0x0
[2025-04-14 09:28:58.547]: Info: Creating encoder [hevc_vaapi]
[2025-04-14 09:28:58.547]: Info: Color coding: SDR (Rec. 601)
[2025-04-14 09:28:58.547]: Info: Color depth: 8-bit
[2025-04-14 09:28:58.547]: Info: Color range: MPEG
[2025-04-14 09:28:58.570]: Info: vaapi vendor: Mesa Gallium driver 25.0.3 for AMD Radeon Graphics (radeonsi, phoenix, LLVM 17.0.6, DRM 3.59, 6.8.0-57-generic)
[2025-04-14 09:28:58.571]: Info: Using normal encoding mode
[2025-04-14 09:28:58.571]: Info: Using default rate control
[2025-04-14 09:28:58.710]: Info: Gamepad 0 will be Nintendo Pro controller (auto-selected by client-reported type)
[2025-04-14 09:28:58.711]: Warning: Unable to create virtual Switch Pro controller: Permission denied
[2025-04-14 09:28:58.711]: Info: Gamepad 0 will be Xbox One controller (default)
[2025-04-14 09:28:58.711]: Warning: Unable to create virtual Xbox One controller: Permission denied
[2025-04-14 09:28:58.711]: Warning: ControllerNumber [] not allocated
[2025-04-14 09:28:58.885]: Warning: ControllerNumber [] not allocated
[2025-04-14 09:28:59.038]: Info: Setting default sink to: [sink-sunshine-stereo]
[2025-04-14 09:28:59.039]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2025-04-14 09:28:59.063]: Info: Opus initialized: 48 kHz, 2 channels, 96 kbps (total), LOWDELAY
[2025-04-14 09:29:55.021]: Info: CLIENT DISCONNECTED
[2025-04-14 09:29:55.021]: Info: Setting default sink to: [alsa_output.pci-0000_65_00.1.HiFi__hw_Generic_3__sink]
```

**Comment by ReenigneArcher** [comment]
I think this was already fixed in the beta/pre-releases. Can you test that?

**Comment by patach** [comment]
Thank you for the reply.

Unfortunately, I installed Version v2025.414.181259, and the problem persists.

Logs:

```
[2025-04-14 14:05:24.283]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2025-04-14 14:05:24.283]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2025-04-14 14:05:24.283]: Info: Found AV1 encoder: av1_vaapi [vaapi]
[2025-04-14 14:05:24.283]: Info: Executing [Desktop]
[2025-04-14 14:05:24.366]: Info: New streaming session started [active sessions: 1]
[2025-04-14 14:05:24.366]: Warning: Unable to create virtual touch screen: Permission denied
[2025-04-14 14:05:24.366]: Warning: Unable to create virtual pen tablet: Permission denied
[2025-04-14 14:05:24.385]: Info: CLIENT CONNECTED
[2025-04-14 14:05:24.386]: Info: Detecting displays
[2025-04-14 14:05:24.392]: Info: Detected display: DisplayPort-0 (id: 0)DisplayPort-0 connected: true
[2025-04-14 14:05:24.392]: Info: Detected display: HDMI-A-0 (id: 1)HDMI-A-0 connected: false
[2025-04-14 14:05:24.392]: Info: Detected display: DisplayPort-1 (id: 2)DisplayPort-1 connected: false
[2025-04-14 14:05:24.392]: Info: Detected display: DisplayPort-2 (id: 3)DisplayPort-2 connected: false
[2025-04-14 14:05:24.392]: Info: Detected display: DisplayPort-3 (id: 4)DisplayPort-3 connected: false
[2025-04-14 14:05:24.392]: Info: Detected display: DisplayPort-4 (id: 5)DisplayPort-4 connected: false
[2025-04-14 14:05:24.392]: Info: Detected display: DisplayPort-5 (id: 6)DisplayPort-5 connected: false
[2025-04-14 14:05:24.393]: Info: Screencasting with X11
[2025-04-14 14:05:24.393]: Info: Configuring selected display (0) to stream
[2025-04-14 14:05:24.399]: Info: Streaming display: DisplayPort-0 with res 3840x2160 offset by 0x0
[2025-04-14 14:05:24.400]: Info: Creating encoder [hevc_vaapi]
[2025-04-14 14:05:24.400]: Info: Color coding: SDR (Rec. 601)
[2025-04-14 14:05:24.400]: Info: Color depth: 8-bit
[2025-04-14 14:05:24.400]: Info: Color range: MPEG
[2025-04-14 14:05:24.424]: Info: vaapi vendor: Mesa Gallium driver 25.0.3 for AMD Radeon Graphics (radeonsi, phoenix, LLVM 17.0.6, DRM 3.59, 6.8.0-57-generic)
[2025-04-14 14:05:24.425]: Info: Streaming bitrate is 7308000
[2025-04-14 14:05:24.425]: Info: Using normal encoding mode
[2025-04-14 14:05:24.425]: Info: Using default rate control
[2025-04-14 14:05:24.568]: Info: Gamepad 0 will be Nintendo Pro controller (auto-selected by client-reported type)
[2025-04-14 14:05:24.568]: Warning: Unable to create virtual Switch Pro controller: Permission denied
[2025-04-14 14:05:24.568]: Info: Gamepad 0 will be Xbox One controller (default)
[2025-04-14 14:05:24.568]: Warning: Unable to create virtual Xbox One controller: Permission denied
[2025-04-14 14:05:24.568]: Warning: ControllerNumber [] not allocated
[2025-04-14 14:05:24.744]: Warning: ControllerNumber [] not allocated
[2025-04-14 14:05:24.848]: Info: Setting default sink to: [sink-sunshine-stereo]
[2025-04-14 14:05:24.849]: Info: Found default monitor by name: sink-sunshine-stereo.monitor
[2025-04-14 14:05:24.870]: Info: Opus initialized: 48 kHz, 2 channels, 96 kbps (total), LOWDELAY
[2025-04-14 14:05:49.140]: Info: CLIENT DISCONNECTED
[2025-04-14 14:05:49.144]: Info: Setting default sink to: [alsa_output.pci-0000_65_00.1.HiFi__hw_Generic_3__sink]
```

**Comment by patach** [comment]
Update on this:

I have uninstalled the flatpak and installed the deb version of Sunshine, after installing the libcuuc dependencies, I was able to get the deb version working perfectly without any issues.

**Comment by ReenigneArcher** [comment]
I think you just forgot to run the flatpak additional install command? It's listed in our docs and the flathub landing page.
