### ISSUE TITLE
[AMD/LINUX] Massive bitrate excursions when displaying mostly static content

### ISSUE THREAD

**Issue by hanneshoch3** [LizardByte/Sunshine#3817]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

This issue is present in the latest pre-release

### Describe the Bug

When I use sunlight to stream over a 56 mbit/s connection with ~35 mbit/s set in Moonlight, everything works fine as long as there is lots of movement. When I open a map ingame for example and the picture becomes mostly static I can observe massive packet loss on the client side and massive bitrate excursions host side (via mangohud overlay), up to 90 mbit/s.
I tried all H/W encoders (H265, HEVC, AV1) on my 7900XT and the all show the same issue. I set the strict bitrate for AMD GPU in vaapi settings, but there is no difference at all. I also tried to set a higher minimum FPS limit (which increased minimum observed bandwidth), but also did not help at all.
Using software encoding it all works just as expected.
I run Arch and tried both sunshine and sunshine-git, as well as mesa and mesa-git, no differences.

### Expected Behavior

No bitrate excursions and thus no frame/packetloss.

### Host Operating System

Linux

### Operating System Version

Arch

### Architecture

amd64/x86_64

### Sunshine commit or version

2̶0̶2̶4̶.̶1̶1̶0̶2̶.̶1̶9̶0̶0̶0̶4̶.̶r̶0̶.̶g̶3̶9̶b̶a̶b̶4̶5̶-̶1̶

2025.426.10137.r0.gc6f3647-1

### Package

Linux - AUR (Third Party)

### GPU Type

AMD

### GPU Model

7900XT

### GPU Driver/Mesa Version

25.2.0_devel.204732.47db31b5564.d41d8cd-1

### Capture Method

None

### Config

```Shell
adapter_name = /dev/dri/renderD128
address_family = both
channels = 1
fec_percentage = 25
fps = [30,60,90,120,144]
lan_encryption_mode = 2
min_threads = 8
notify_pre_releases = enabled
qp = 29
resolutions = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    3840x2160,
    2560x1440,
    3120x1440
]
sw_preset = ultrafast
upnp = enabled
vaapi_strict_rc_buffer = enabled
wan_encryption_mode = 2
```

### Apps

```json

```

### Relevant log output

```shell
[2025-04-27 15:44:35.271]: Info: Video encryption enabled
[2025-04-27 15:44:35.271]: Info: New streaming session started [active sessions: 1]
[2025-04-27 15:44:35.501]: Info: Found default monitor by name: bluez_output.F4_9D_8A_09_CD_47.1.monitor
[2025-04-27 15:44:35.504]: Info: CLIENT CONNECTED
[2025-04-27 15:44:35.508]: Info: /dev/dri/card1 -> amdgpu
[2025-04-27 15:44:35.509]: Info: /dev/dri/card0 -> amdgpu
[2025-04-27 15:44:35.509]: Info: Found display [wayland-0]
[2025-04-27 15:44:35.509]: Info: Found interface: zxdg_output_manager_v1(31) version 3
[2025-04-27 15:44:35.509]: Info: Found interface: zwp_linux_dmabuf_v1(52) version 4
[2025-04-27 15:44:35.509]: Info: Found interface: wl_output(59) version 4
[2025-04-27 15:44:35.509]: Info: Resolution: 3840x2160
[2025-04-27 15:44:35.509]: Info: Offset: 0x0
[2025-04-27 15:44:35.509]: Info: Logical size: 2560x1440
[2025-04-27 15:44:35.509]: Info: Name: DP-1
[2025-04-27 15:44:35.509]: Info: Found monitor: ASUSTek COMPUTER INC VG28UQL1A
[2025-04-27 15:44:35.509]: Info: -------- Start of KMS monitor list --------
[2025-04-27 15:44:35.509]: Info: --------- End of KMS monitor list ---------
[2025-04-27 15:44:35.509]: Info: Screencasting with KMS
[2025-04-27 15:44:35.510]: Info: /dev/dri/card1 -> amdgpu
[2025-04-27 15:44:35.510]: Info: /dev/dri/card0 -> amdgpu
[2025-04-27 15:44:35.510]: Info: Found monitor for DRM screencasting
[2025-04-27 15:44:35.510]: Info: Found connector ID [107]
[2025-04-27 15:44:35.510]: Info: Found cursor plane [90]
[2025-04-27 15:44:35.514]: Info: Creating encoder [av1_vaapi]
[2025-04-27 15:44:35.514]: Info: Color coding: SDR (Rec. 601)
[2025-04-27 15:44:35.514]: Info: Color depth: 8-bit
[2025-04-27 15:44:35.514]: Info: Color range: MPEG
[2025-04-27 15:44:35.515]: Info: Opus initialized: 48 kHz, 2 channels, 512 kbps (total), LOWDELAY
[2025-04-27 15:44:35.521]: Info: vaapi vendor: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.61, 6.14.4-1-cachyos)
[2025-04-27 15:44:35.522]: Info: Streaming bitrate is 23363000
[2025-04-27 15:44:35.522]: Info: Using normal encoding mode
[2025-04-27 15:44:35.522]: Info: Using VBR with single frame VBV size
[2025-04-27 15:44:35.522]: Warning: [av1_vaapi @ 0x705bb0006bc0] Multiple slices were requested but this codec does not support controlling slices.
[2025-04-27 15:44:46.021]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:46.137]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:46.571]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:46.937]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:47.304]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:48.952]: Warning: Skipping FEC for abnormally large encoded frame (needed 6 FEC blocks)
[2025-04-27 15:44:49.038]: Warning: Skipping FEC for abnormally large encoded frame (needed 6 FEC blocks)
[2025-04-27 15:44:49.735]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:49.838]: Warning: Skipping FEC for abnormally large encoded frame (needed 7 FEC blocks)
[2025-04-27 15:44:50.402]: Warning: Skipping FEC for abnormally large encoded frame (needed 6 FEC blocks)
[2025-04-27 15:44:51.302]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:51.452]: Warning: Skipping FEC for abnormally large encoded frame (needed 6 FEC blocks)
[2025-04-27 15:44:52.121]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:52.418]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:56.985]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:57.072]: Warning: Skipping FEC for abnormally large encoded frame (needed 7 FEC blocks)
[2025-04-27 15:44:57.206]: Warning: Skipping FEC for abnormally large encoded frame (needed 7 FEC blocks)
[2025-04-27 15:44:57.702]: Warning: Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)
[2025-04-27 15:44:57.789]: Warning: Skipping FEC for abnormally large encoded frame (needed 7 FEC blocks)
```

**Comment by ReenigneArcher** [comment]
> 2024.1102.190004.r0.g39bab45-1

Time to update, this is very outdated.

**Comment by hanneshoch3** [comment]
Whoops sorry, I must've copied the wrong text: 2025.426.10137.r0.gc6f3647-1

**Comment by hanneshoch3** [comment]
So, thanks to your report on windows I got to thinking, maybe it was an AMD Firmware Issue. I still have some old firmware-linux packages, so I tried to just downgrade to linux-firmware-20241210.b00a7f7e-1, since I knew it was working around christmas time.

In a short test, it seems to be working again now. So maybe it is an AMD firmware issue? Can you try to install an older windows AMD driver, in the hopes it will also downgrade GPU firmware for you and try again? Might not be a sunshine bug at all, but I haven't tested too much yet.

**Comment by Slashic** [comment]
It may be an AMD driver issue indeed, but the fact that the Linux driver and Windows drivers behave the same way is quite strange, i'll try streaming from Fedora 41 on the same machine, but Sunshine on Linux isn't at Windows level yet in terms of performances.

Also, there's no "firmware downgrade" involved, everything is software based even on Linux, kernel drivers and Windows drivers never touches the VBIOS, it's often partly overrided by the driver itself, so just putting another version will suffice.

**Comment by hanneshoch3** [comment]
Nevermind my firmware comment, further testing showed no difference at all.

**Comment by Slashic** [comment]
Same behavior with v2025.509.184504:

`Skipping FEC for abnormally large encoded frame`

Then stream crashes with error -1 on Moonlight.

Configuration used:

```
[2025-05-11 20:27:04.385]: Info: Sunshine version: v2025.509.184504
[2025-05-11 20:27:04.385]: Info: Package Publisher: LizardByte
[2025-05-11 20:27:04.385]: Info: Publisher Website: https://app.lizardbyte.dev
[2025-05-11 20:27:04.385]: Info: Get support: https://app.lizardbyte.dev/support
[2025-05-11 20:27:04.385]: Info: config: 'output_name' = {da41159a-36a2-5bab-a18b-c52bbce27ee7}
[2025-05-11 20:27:04.385]: Info: config: 'min_log_level' = 2
[2025-05-11 20:27:04.386]: Info: config: 'sunshine_name' = Slash (Windows)
[2025-05-11 20:27:04.386]: Info: config: 'always_send_scancodes' = disabled
[2025-05-11 20:27:04.386]: Info: config: 'amd_enforce_hrd' = enabled
[2025-05-11 20:27:04.386]: Info: config: 'amd_quality' = speed
[2025-05-11 20:27:04.386]: Info: config: 'encoder' = amdvce
[2025-05-11 20:27:04.386]: Info: config: 'hevc_mode' = 3
[2025-05-11 20:27:04.386]: Info: config: 'av1_mode' = 3
[2025-05-11 20:27:04.386]: Info: config: 'amd_rc' = cbr
[2025-05-11 20:27:04.386]: Info: config: 'dd_hdr_option' = disabled
[2025-05-11 20:27:04.386]: Info: config: 'motion_as_ds4' = disabled
[2025-05-11 20:27:04.386]: Info: config: 'touchpad_as_ds4' = disabled
[2025-05-11 20:27:04.386]: Info: config: 'dd_configuration_option' = ensure_only_display
[2025-05-11 20:27:04.386]: Info: config: 'fec_percentage' = 0
```

HRD does not change this, nor setting CBR (+ HRD)

**Comment by Slashic** [comment]
After some extensive testing, i went through some old builds because I remembered this issue appeared around October 2024:

I wasn't able to reproduce the issue with version 0.23.1, nor v2024.1004.14216 (10th of October 2024 nightly)
With v2024.1107.45727 (07th of November 2024) i was able to instantly reproduce the issue.

After having a look at commits between these two builds, I heavily suspect FFmpeg update to 7.1 is the one causing this issue: https://github.com/LizardByte/Sunshine/commit/011a872c889999dc2ce8e552488d3d3011426c94

I may be wrong but this is the only major commit done on video encoding between these two builds.

**Comment by Slashic** [comment]
**Update**: I finally managed to reproduce the issue with v2024.1004.14216, although the issue seems less frequent for some reason, it's not the FFmpeg update or at least it's not entirely due to that, unfortunately the gap is too wide with 0.23.1 and a lot changed as well.

**Comment by gschintgen** [comment]
I think I can confirm that there's been a significant regression on AMD/Linux. I'm on Ubuntu 24.04 (with kisak-mesa, but otherwise stock) and here's what I observed when I came back to Sunshine after a longer break:

Current release (v2025.122.141614) has issues as described in the OP: in slower moving parts, e.g. in the menus before and after a race in a racing game, there's a lot of packet loss shown by moonlight-qt and the stream is stuttery and the "Slow connection" warning is shown frequently or even most of the time. During the races it's better but not perfect (some packet loss was present but not as catastrophically). I tried without and without the strict bandwidth limiting, h264 and h265, and was not really satisfied even though it was playable.

I then tried the latest pre-release but it's not satisfactory either (same symptoms). I tried 0.23.1 but it didn't work at all (at first there were missing dependencies and after having installed the missing libs it would still crash immediately at application startup). So no currently available public build for Ubuntu 24.04 is working correctly as far as I can tell.

Fortunately I still had an older build artifact lying around: commit 6c483429b3819aa07ace4f4b66f2af8fd16ca69f of PR #3115.
That version is working great for me! In other words the regression seems to have been introduced **between 1st September 2024 and 22nd January 2025**.

**Comment by ReenigneArcher** [comment]
@gschintgen can you test out this PR? https://github.com/LizardByte/Sunshine/pull/3844

**Comment by gschintgen** [comment]
> [@gschintgen](https://github.com/gschintgen) can you test out this PR? [#3844](https://github.com/LizardByte/Sunshine/pull/3844)

First I'll try to track down where the regression is even coming from. (I'm not sure all that minimum frame rate stuff has an impact here, the in-game menus are not static, there's just less motion.)

I thought it might be coming from ffmpeg 7.1, but no. Commit 1c2123650f (October 20) is still perfectly fine for me. (It includes ffmpeg 7.1 and the related patches that came a few days later.) I'll do a git bisect, but the results won't be for today.

**Comment by gschintgen** [comment]
I did some bisecting and validating and here are my preliminary conclusions. It's getting late though... Any confirmation would be appreciated.

Up to commit 9662f0547f11 (Nov. 1) the stream is rock solid. As an objective measure for "solid" I mean that "Frames dropped by your network connection" as shown by moonlight-qt's OSD is stuck at a clean 0.00%. (I also playtested various commits quite a bit to confirm both behaviours: "solid" and "erratic".)

When I move up to commit 9e52ac426df1e (**also Nov. 1: "feat(vaapi): add option to enable strict enforcement of frame size") streaming performance becomes quite erratic**, "Frames dropped" often fluctuates between 0 and ~40%(!) and the stream becomes stuttery and the red "Slow connection" warning appears.

(I hope I'm not misinterpreting commit dates and merge dates, etc.)

It is my understanding that in July 2024 there was a merge of a fix for bitrate overshoots (see #2821) and that this fixed rate control has been in place until the newer fix (?) was merged on 1st November. (PR #3332). As such builds between July and end of October are supposed to have proper bitrate handling at the price of possible image quality regressions (see #2864).

I therefore based my testing scenario on an "Enabled" strict bitrate control setting in the VAAPI tab in Sunshine's WebUI (for commits that have this option in place) in order to have a hopefully fair comparison between commits before and after the relevant changes.

I'm using a RX6650 (RDNA2) card as that is the only one at my disposal. I chose 1080p, 80MBit/s, h265 for my testing (over 1GBps-Ethernet).

I could do some more (re)testing (in particular with disabled strict rate control), post sunshine logs before and after, etc. but that's for another day. Any insight (or request for further testing) would be appreciated. In particular from @cgutman :-)

**Comment by ReenigneArcher** [comment]
Thanks for digging into this.

> I hope I'm not misinterpreting commit dates and merge dates, etc.

We started doing squash merging last year, so the merge and commit date are the same (as long as the PR number is in the commit title)

**Comment by cgutman** [comment]
So you're seeing bitrate excursions even with the VAAPI strict bitrate enforcement option enabled? Please post your logs with debug  log level so we can see what rate control and VBV size was chosen by Sunshine and FFmpeg.

It would also be useful to get these logs both from https://github.com/LizardByte/Sunshine/commit/9662f0547f116bdd6870ec7c8ab246e95572585f and from the latest version of Sunshine, so we can compare them.

**Comment by rikiguan** [comment]
I encountered a similar issue: on Ubuntu 24.04, Sunshine uses significantly more bandwidth than the maximum bitrate I configured whenever there are transition animations in the GNOME interface. It seems like my bitrate settings have no effect. In some cases, this causes my Moonlight connection to freeze, although the mouse can still move. I suspect the issue lies with Wayland's rendering or refresh logic.

**Comment by hanneshoch3** [comment]
I hope this is what you meant.

```
[2025-06-11 19:32:25.742]: Info: Sunshine version: v2025.608.232654
[2025-06-11 19:32:25.742]: Info: Package Publisher: LizardByte
[2025-06-11 19:32:25.742]: Info: Publisher Website: https://app.lizardbyte.dev
[2025-06-11 19:32:25.742]: Info: Get support: https://app.lizardbyte.dev/support
[2025-06-11 19:32:25.742]: Info: config: 'qp' = 29
[2025-06-11 19:32:25.742]: Info: config: 'fec_percentage' = 30
[2025-06-11 19:32:25.742]: Info: config: 'notify_pre_releases' = enabled
[2025-06-11 19:32:25.742]: Info: config: 'channels' = 1
[2025-06-11 19:32:25.742]: Info: config: 'wan_encryption_mode' = 2
[2025-06-11 19:32:25.742]: Info: config: 'sw_preset' = ultrafast
[2025-06-11 19:32:25.742]: Info: config: 'upnp' = enabled
[2025-06-11 19:32:25.742]: Info: config: 'adapter_name' = /dev/dri/renderD128
[2025-06-11 19:32:25.742]: Info: config: 'capture' = kms
[2025-06-11 19:32:25.742]: Info: config: 'resolutions' = [
    352x240,
    480x360,
    858x480,
    1280x720,
    1920x1080,
    3840x2160,
    2560x1440,
    3120x1440
]
[2025-06-11 19:32:25.742]: Info: config: 'address_family' = both
[2025-06-11 19:32:25.742]: Info: config: 'vaapi_strict_rc_buffer' = enabled
[2025-06-11 19:32:25.742]: Info: config: 'fps' = [30,60,90,120,144]
[2025-06-11 19:32:25.742]: Info: config: 'min_fps_factor' = 2
[2025-06-11 19:32:25.742]: Info: config: 'lan_encryption_mode' = 2
[2025-06-11 19:32:25.742]: Info: config: 'min_log_level' = 1
[2025-06-11 19:32:25.742]: Info: config: 'min_threads' = 8
[2025-06-11 19:32:25.751]: Info: /dev/dri/card0 -> amdgpu
[2025-06-11 19:32:25.751]: Debug: Opening render node: /dev/dri/renderD128
[2025-06-11 19:32:25.751]: Debug: crtc(0, 0)
[2025-06-11 19:32:25.751]: Debug: crtc(3840, 2160)
[2025-06-11 19:32:25.751]: Debug: plane->possible_crtcs == 1
[2025-06-11 19:32:25.751]: Debug: x(0) y(0) crtc_x(0) crtc_y(0) crtc_id(93)
[2025-06-11 19:32:25.751]: Debug: Resolution: 3840x2160: Pitch: 30720: Offset: 0
[2025-06-11 19:32:25.751]: Debug: Format [XR24, AR24, RA24, XR30, XB30, AR30, AB30, XR48, XB48, AR48, AB48, XB24, AB24, RG16, NV12, P010, XR4H, AR4H, XB4H, AB4H]
[2025-06-11 19:32:25.752]: Info: Found display [wayland-0]
[2025-06-11 19:32:25.752]: Info: Found display [wayland-0]
[2025-06-11 19:32:25.752]: Debug: Available interface: wl_compositor(1) version 6
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_tablet_manager_v2(3) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_keyboard_shortcuts_inhibit_manager_v1(4) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zxdg_decoration_manager_v1(5) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_viewporter(6) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_security_context_manager_v1(7) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_fractional_scale_manager_v1(8) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wl_shm(9) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wl_seat(10) version 9
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_pointer_gestures_v1(11) version 3
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_pointer_constraints_v1(12) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_relative_pointer_manager_v1(13) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wl_data_device_manager(14) version 3
[2025-06-11 19:32:25.752]: Debug: Available interface: zwlr_data_control_manager_v1(15) version 2
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_cursor_shape_manager_v1(16) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_primary_selection_device_manager_v1(17) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_idle(18) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_idle_inhibit_manager_v1(19) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: ext_idle_notifier_v1(20) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_plasma_shell(21) version 8
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_appmenu_manager(22) version 2
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_server_decoration_palette_manager(23) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_plasma_virtual_desktop_management(25) version 2
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_shadow_manager(27) version 2
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_dpms_manager(28) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_server_decoration_manager(29) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: kde_output_management_v2(30) version 12
[2025-06-11 19:32:25.752]: Debug: Available interface: zxdg_output_manager_v1(31) version 3
[2025-06-11 19:32:25.752]: Info: Found interface: zxdg_output_manager_v1(31) version 3
[2025-06-11 19:32:25.752]: Debug: Available interface: wl_subcompositor(32) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zxdg_exporter_v2(33) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zxdg_importer_v2(34) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: xdg_activation_v1(37) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_content_type_manager_v1(39) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_tearing_control_manager_v1(40) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: xdg_toplevel_drag_manager_v1(41) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: xdg_toplevel_icon_manager_v1(42) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: kde_screen_edge_manager_v1(43) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: frog_color_management_factory_v1(44) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_presentation(45) version 2
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_color_manager_v1(46) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: xdg_wm_dialog_v1(47) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: kde_external_brightness_v1(48) version 2
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_alpha_modifier_v1(49) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: wl_drm(51) version 2
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_linux_dmabuf_v1(52) version 4
[2025-06-11 19:32:25.752]: Info: Found interface: zwp_linux_dmabuf_v1(52) version 4
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_linux_drm_syncobj_manager_v1(53) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: xdg_wm_base(55) version 6
[2025-06-11 19:32:25.752]: Debug: Available interface: zwlr_layer_shell_v1(56) version 5
[2025-06-11 19:32:25.752]: Debug: Available interface: kde_output_device_v2(58) version 11
[2025-06-11 19:32:25.752]: Debug: Available interface: wl_output(59) version 4
[2025-06-11 19:32:25.752]: Info: Found interface: wl_output(59) version 4
[2025-06-11 19:32:25.752]: Debug: Available interface: wp_drm_lease_device_v1(60) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: kde_output_order_v1(61) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_text_input_manager_v1(62) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_text_input_manager_v2(63) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: zwp_text_input_manager_v3(64) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_blur_manager(66) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_contrast_manager(67) version 2
[2025-06-11 19:32:25.752]: Debug: Available interface: org_kde_kwin_slide_manager(68) version 1
[2025-06-11 19:32:25.752]: Debug: Available interface: xdg_system_bell_v1(69) version 1
[2025-06-11 19:32:25.752]: Info: Resolution: 3840x2160
[2025-06-11 19:32:25.752]: Info: Offset: 0x0
[2025-06-11 19:32:25.752]: Info: Logical size: 2560x1440
[2025-06-11 19:32:25.752]: Info: Name: DP-1
[2025-06-11 19:32:25.752]: Info: Found monitor: ASUSTek COMPUTER INC VG28UQL1A
[2025-06-11 19:32:25.752]: Info: -------- Start of KMS monitor list --------
[2025-06-11 19:32:25.752]: Info: Monitor 0 is DP-1: ASUSTek COMPUTER INC VG28UQL1A
[2025-06-11 19:32:25.752]: Info: --------- End of KMS monitor list ---------
[2025-06-11 19:32:25.752]: Debug: Monitor description
[2025-06-11 19:32:25.752]: Debug: Resolution: 0x0
[2025-06-11 19:32:25.752]: Debug: Offset: 0x0
[2025-06-11 19:32:25.752]: Debug: Monitor description
[2025-06-11 19:32:25.752]: Debug: Resolution: 3840x2160
[2025-06-11 19:32:25.752]: Debug: Offset: 0x0
[2025-06-11 19:32:25.752]: Debug: Desktop resolution: 3840x2160
[2025-06-11 19:32:25.770]: Info: System tray created
[2025-06-11 19:32:25.770]: Debug: System tray loop
[2025-06-11 19:32:25.770]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.771]: Debug: System tray loop
[2025-06-11 19:32:25.772]: Debug: System tray loop
[2025-06-11 19:32:25.772]: Debug: System tray loop
[2025-06-11 19:32:25.782]: Debug: System tray loop
[2025-06-11 19:32:25.783]: Debug: System tray loop
[2025-06-11 19:32:25.871]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2025-06-11 19:32:25.871]: Info: Trying encoder [nvenc]
[2025-06-11 19:32:25.871]: Info: Screencasting with KMS
[2025-06-11 19:32:25.871]: Info: /dev/dri/card0 -> amdgpu
[2025-06-11 19:32:25.871]: Debug: Opening render node: /dev/dri/renderD128
[2025-06-11 19:32:25.871]: Debug: "card0" is not a CUDA device
[2025-06-11 19:32:25.871]: Error: Couldn't find monitor [0]
[2025-06-11 19:32:25.871]: Info: /dev/dri/card0 -> amdgpu
[2025-06-11 19:32:25.871]: Debug: Opening render node: /dev/dri/renderD128
[2025-06-11 19:32:25.871]: Debug: "card0" is not a CUDA device
[2025-06-11 19:32:25.871]: Error: Couldn't find monitor [0]
[2025-06-11 19:32:26.071]: Info: Screencasting with KMS
[2025-06-11 19:32:26.071]: Info: /dev/dri/card0 -> amdgpu
[2025-06-11 19:32:26.071]: Debug: Opening render node: /dev/dri/renderD128
[2025-06-11 19:32:26.071]: Debug: "card0" is not a CUDA device
[2025-06-11 19:32:26.072]: Error: Couldn't find monitor [0]
[2025-06-11 19:32:26.072]: Info: /dev/dri/card0 -> amdgpu
[2025-06-11 19:32:26.072]: Debug: Opening render node: /dev/dri/renderD128
[2025-06-11 19:32:26.072]: Debug: "card0" is not a CUDA device
[2025-06-11 19:32:26.072]: Error: Couldn't find monitor [0]
[2025-06-11 19:32:26.272]: Info: Encoder [nvenc] failed
[2025-06-11 19:32:26.272]: Info: Trying encoder [vaapi]
[2025-06-11 19:32:26.272]: Info: Screencasting with KMS
[2025-06-11 19:32:26.272]: Info: /dev/dri/card0 -> amdgpu
[2025-06-11 19:32:26.272]: Debug: Opening render node: /dev/dri/renderD128
[2025-06-11 19:32:26.272]: Info: Found monitor for DRM screencasting
[2025-06-11 19:32:26.272]: Debug: crtc(0, 0)
[2025-06-11 19:32:26.272]: Debug: crtc(3840, 2160)
[2025-06-11 19:32:26.272]: Debug: plane->possible_crtcs == 1
[2025-06-11 19:32:26.272]: Debug: x(0) y(0) crtc_x(0) crtc_y(0) crtc_id(93)
[2025-06-11 19:32:26.272]: Debug: Resolution: 3840x2160: Pitch: 30720: Offset: 0
[2025-06-11 19:32:26.272]: Debug: Format [XR24, AR24, RA24, XR30, XB30, AR30, AB30, XR48, XB48, AR48, AB48, XB24, AB24, RG16, NV12, P010, XR4H, AR4H, XB4H, AB4H]
[2025-06-11 19:32:26.272]: Info: Found connector ID [107]
[2025-06-11 19:32:26.272]: Info: Found cursor plane [90]
[2025-06-11 19:32:26.278]: Info: Creating encoder [h264_vaapi]
[2025-06-11 19:32:26.278]: Info: Color coding: SDR (Rec. 601)
[2025-06-11 19:32:26.278]: Info: Color depth: 8-bit
[2025-06-11 19:32:26.278]: Info: Color range: JPEG
[2025-06-11 19:32:26.281]: Debug: EGL: [Mesa Project]: version [1.5]
[2025-06-11 19:32:26.281]: Debug: API's supported: [OpenGL OpenGL_ES ]
[2025-06-11 19:32:26.283]: Debug: GL: vendor: AMD
[2025-06-11 19:32:26.283]: Debug: GL: renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.283]: Debug: GL: version: 4.6 (Compatibility Profile) Mesa 25.2.0-devel (git-19e494a461)
[2025-06-11 19:32:26.283]: Debug: GL: shader: 4.60
[2025-06-11 19:32:26.284]: Info: vaapi vendor: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.284]: Debug: [AVHWDeviceContext @ 0x64f0a0355b40] VAAPI driver: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos).
[2025-06-11 19:32:26.284]: Debug: [AVHWDeviceContext @ 0x64f0a0355b40] Driver not found in known nonstandard list, using standard behaviour.
[2025-06-11 19:32:26.285]: Info: Streaming bitrate is 1000000
[2025-06-11 19:32:26.285]: Info: Using normal encoding mode
[2025-06-11 19:32:26.285]: Info: Using VBR with single frame VBV size
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] Input surface format is nv12.
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] Using VAAPI profile VAProfileH264High (7).
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] Using VAAPI render target format YUV420 (0x1).
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] RC mode: VBR.
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] Block Level bitrate control: OFF.
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] RC target: 100% of 1000000 bps over 16 ms.
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] RC buffer: 16666 bits, initial fullness 12499 bits.
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] RC framerate: 60/1 (60,00 fps).
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] Driver does not report any additional prediction constraints.
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] Using intra and P-frames (supported references: 1 / 1).
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] All wanted packed headers available (wanted 0xd, found 0x1f).
[2025-06-11 19:32:26.285]: Debug: [h264_vaapi @ 0x64f09fff4000] Using level 4.2.
[2025-06-11 19:32:26.296]: Debug: Frame 1: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2025-06-11 19:32:26.300]: Info: Creating encoder [hevc_vaapi]
[2025-06-11 19:32:26.300]: Info: Color coding: SDR (Rec. 601)
[2025-06-11 19:32:26.300]: Info: Color depth: 8-bit
[2025-06-11 19:32:26.300]: Info: Color range: JPEG
[2025-06-11 19:32:26.304]: Debug: EGL: [Mesa Project]: version [1.5]
[2025-06-11 19:32:26.304]: Debug: API's supported: [OpenGL OpenGL_ES ]
[2025-06-11 19:32:26.305]: Debug: GL: vendor: AMD
[2025-06-11 19:32:26.305]: Debug: GL: renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.305]: Debug: GL: version: 4.6 (Compatibility Profile) Mesa 25.2.0-devel (git-19e494a461)
[2025-06-11 19:32:26.305]: Debug: GL: shader: 4.60
[2025-06-11 19:32:26.307]: Info: vaapi vendor: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.307]: Debug: [AVHWDeviceContext @ 0x64f0a02f3dc0] VAAPI driver: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos).
[2025-06-11 19:32:26.307]: Debug: [AVHWDeviceContext @ 0x64f0a02f3dc0] Driver not found in known nonstandard list, using standard behaviour.
[2025-06-11 19:32:26.307]: Info: Streaming bitrate is 1000000
[2025-06-11 19:32:26.307]: Info: Using normal encoding mode
[2025-06-11 19:32:26.307]: Info: Using VBR with single frame VBV size
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Input surface format is nv12.
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using VAAPI profile VAProfileHEVCMain (17).
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using VAAPI render target format YUV420 (0x1).
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using CTU size 64x64, min CB size 8x8.
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] RC mode: VBR.
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Block Level bitrate control: OFF.
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] RC target: 100% of 1000000 bps over 16 ms.
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] RC buffer: 16666 bits, initial fullness 12499 bits.
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] RC framerate: 60/1 (60,00 fps).
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Driver does not report any additional prediction constraints.
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using intra and P-frames (supported references: 1 / 0).
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] All wanted packed headers available (wanted 0xd, found 0x1f).
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using customized alignment size [64x16].
[2025-06-11 19:32:26.307]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using level 4.
[2025-06-11 19:32:26.316]: Debug: Frame 1: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2025-06-11 19:32:26.319]: Info: Creating encoder [av1_vaapi]
[2025-06-11 19:32:26.319]: Info: Color coding: SDR (Rec. 601)
[2025-06-11 19:32:26.319]: Info: Color depth: 8-bit
[2025-06-11 19:32:26.319]: Info: Color range: JPEG
[2025-06-11 19:32:26.323]: Debug: EGL: [Mesa Project]: version [1.5]
[2025-06-11 19:32:26.323]: Debug: API's supported: [OpenGL OpenGL_ES ]
[2025-06-11 19:32:26.324]: Debug: GL: vendor: AMD
[2025-06-11 19:32:26.324]: Debug: GL: renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.324]: Debug: GL: version: 4.6 (Compatibility Profile) Mesa 25.2.0-devel (git-19e494a461)
[2025-06-11 19:32:26.324]: Debug: GL: shader: 4.60
[2025-06-11 19:32:26.325]: Info: vaapi vendor: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.325]: Debug: [AVHWDeviceContext @ 0x64f09fff5240] VAAPI driver: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos).
[2025-06-11 19:32:26.325]: Debug: [AVHWDeviceContext @ 0x64f09fff5240] Driver not found in known nonstandard list, using standard behaviour.
[2025-06-11 19:32:26.325]: Info: Streaming bitrate is 1000000
[2025-06-11 19:32:26.325]: Info: Using normal encoding mode
[2025-06-11 19:32:26.325]: Info: Using VBR with single frame VBV size
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] Input surface format is nv12.
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] Using VAAPI profile VAProfileAV1Profile0 (32).
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] Using VAAPI render target format YUV420 (0x1).
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] RC mode: VBR.
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] Block Level bitrate control: OFF.
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] RC target: 100% of 1000000 bps over 16 ms.
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] RC buffer: 16666 bits, initial fullness 12499 bits.
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] RC framerate: 60/1 (60,00 fps).
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] Driver does not report any additional prediction constraints.
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] Using intra and P-frames (supported references: 1 / 0).
[2025-06-11 19:32:26.325]: Warning: [av1_vaapi @ 0x64f09fff4000] Multiple slices were requested but this codec does not support controlling slices.
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] All wanted packed headers available (wanted 0xb, found 0x1b).
[2025-06-11 19:32:26.325]: Debug: [av1_vaapi @ 0x64f09fff4000] Using customized alignment size [64x16].
[2025-06-11 19:32:26.326]: Debug: [av1_vaapi @ 0x64f09fff4000] Using level 4.1.
[2025-06-11 19:32:26.333]: Debug: Frame 1: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2025-06-11 19:32:26.336]: Info: Screencasting with KMS
[2025-06-11 19:32:26.336]: Info: /dev/dri/card0 -> amdgpu
[2025-06-11 19:32:26.336]: Debug: Opening render node: /dev/dri/renderD128
[2025-06-11 19:32:26.336]: Info: Found monitor for DRM screencasting
[2025-06-11 19:32:26.336]: Debug: crtc(0, 0)
[2025-06-11 19:32:26.336]: Debug: crtc(3840, 2160)
[2025-06-11 19:32:26.336]: Debug: plane->possible_crtcs == 1
[2025-06-11 19:32:26.336]: Debug: x(0) y(0) crtc_x(0) crtc_y(0) crtc_id(93)
[2025-06-11 19:32:26.336]: Debug: Resolution: 3840x2160: Pitch: 30720: Offset: 0
[2025-06-11 19:32:26.336]: Debug: Format [XR24, AR24, RA24, XR30, XB30, AR30, AB30, XR48, XB48, AR48, AB48, XB24, AB24, RG16, NV12, P010, XR4H, AR4H, XB4H, AB4H]
[2025-06-11 19:32:26.336]: Info: Found connector ID [107]
[2025-06-11 19:32:26.336]: Info: Found cursor plane [90]
[2025-06-11 19:32:26.339]: Info: Creating encoder [hevc_vaapi]
[2025-06-11 19:32:26.339]: Info: Color coding: HDR (Rec. 2020 + SMPTE 2084 PQ)
[2025-06-11 19:32:26.339]: Info: Color depth: 10-bit
[2025-06-11 19:32:26.339]: Info: Color range: JPEG
[2025-06-11 19:32:26.342]: Debug: EGL: [Mesa Project]: version [1.5]
[2025-06-11 19:32:26.342]: Debug: API's supported: [OpenGL OpenGL_ES ]
[2025-06-11 19:32:26.342]: Debug: GL: vendor: AMD
[2025-06-11 19:32:26.342]: Debug: GL: renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.342]: Debug: GL: version: 4.6 (Compatibility Profile) Mesa 25.2.0-devel (git-19e494a461)
[2025-06-11 19:32:26.342]: Debug: GL: shader: 4.60
[2025-06-11 19:32:26.344]: Info: vaapi vendor: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.344]: Debug: [AVHWDeviceContext @ 0x64f0a0ecac00] VAAPI driver: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos).
[2025-06-11 19:32:26.344]: Debug: [AVHWDeviceContext @ 0x64f0a0ecac00] Driver not found in known nonstandard list, using standard behaviour.
[2025-06-11 19:32:26.345]: Info: Streaming bitrate is 1000000
[2025-06-11 19:32:26.345]: Info: Using normal encoding mode
[2025-06-11 19:32:26.345]: Info: Using VBR with single frame VBV size
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Input surface format is p010le.
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using VAAPI profile VAProfileHEVCMain10 (18).
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using VAAPI render target format YUV420_10 (0x100).
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using CTU size 64x64, min CB size 8x8.
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] RC mode: VBR.
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Block Level bitrate control: OFF.
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] RC target: 100% of 1000000 bps over 16 ms.
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] RC buffer: 16666 bits, initial fullness 12499 bits.
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] RC framerate: 60/1 (60,00 fps).
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Driver does not report any additional prediction constraints.
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using intra and P-frames (supported references: 1 / 0).
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] All wanted packed headers available (wanted 0xd, found 0x1f).
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using customized alignment size [64x16].
[2025-06-11 19:32:26.345]: Debug: [hevc_vaapi @ 0x64f09fff4000] Using level 4.
[2025-06-11 19:32:26.353]: Debug: Frame 1: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2025-06-11 19:32:26.358]: Info: Creating encoder [av1_vaapi]
[2025-06-11 19:32:26.358]: Info: Color coding: HDR (Rec. 2020 + SMPTE 2084 PQ)
[2025-06-11 19:32:26.358]: Info: Color depth: 10-bit
[2025-06-11 19:32:26.358]: Info: Color range: JPEG
[2025-06-11 19:32:26.362]: Debug: EGL: [Mesa Project]: version [1.5]
[2025-06-11 19:32:26.362]: Debug: API's supported: [OpenGL OpenGL_ES ]
[2025-06-11 19:32:26.363]: Debug: GL: vendor: AMD
[2025-06-11 19:32:26.363]: Debug: GL: renderer: AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.363]: Debug: GL: version: 4.6 (Compatibility Profile) Mesa 25.2.0-devel (git-19e494a461)
[2025-06-11 19:32:26.363]: Debug: GL: shader: 4.60
[2025-06-11 19:32:26.364]: Info: vaapi vendor: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos)
[2025-06-11 19:32:26.364]: Debug: [AVHWDeviceContext @ 0x64f0a00e8900] VAAPI driver: Mesa Gallium driver 25.2.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 19.1.7, DRM 3.63, 6.15.1-4-cachyos).
[2025-06-11 19:32:26.364]: Debug: [AVHWDeviceContext @ 0x64f0a00e8900] Driver not found in known nonstandard list, using standard behaviour.
[2025-06-11 19:32:26.364]: Info: Streaming bitrate is 1000000
[2025-06-11 19:32:26.365]: Info: Using normal encoding mode
[2025-06-11 19:32:26.365]: Info: Using VBR with single frame VBV size
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Input surface format is p010le.
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Using VAAPI profile VAProfileAV1Profile0 (32).
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Using VAAPI render target format YUV420_10 (0x100).
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] RC mode: VBR.
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Block Level bitrate control: OFF.
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] RC target: 100% of 1000000 bps over 16 ms.
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] RC buffer: 16666 bits, initial fullness 12499 bits.
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] RC framerate: 60/1 (60,00 fps).
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Driver does not report any additional prediction constraints.
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Using intra and P-frames (supported references: 1 / 0).
[2025-06-11 19:32:26.365]: Warning: [av1_vaapi @ 0x64f09fff4000] Multiple slices were requested but this codec does not support controlling slices.
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] All wanted packed headers available (wanted 0xb, found 0x1b).
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Using customized alignment size [64x16].
[2025-06-11 19:32:26.365]: Debug: [av1_vaapi @ 0x64f09fff4000] Using level 4.1.
[2025-06-11 19:32:26.372]: Debug: Frame 1: IDR Keyframe (AV_FRAME_FLAG_KEY)
[2025-06-11 19:32:26.375]: Info: 
[2025-06-11 19:32:26.375]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2025-06-11 19:32:26.375]: Info: 
[2025-06-11 19:32:26.375]: Debug: ------  h264 ------
[2025-06-11 19:32:26.375]: Debug: PASSED: supported
[2025-06-11 19:32:26.375]: Debug: REF_FRAMES_RESTRICT: supported
[2025-06-11 19:32:26.375]: Debug: DYNAMIC_RANGE: unsupported
[2025-06-11 19:32:26.375]: Debug: YUV444: unsupported
[2025-06-11 19:32:26.375]: Debug: VUI_PARAMETERS: supported
[2025-06-11 19:32:26.375]: Debug: -------------------
[2025-06-11 19:32:26.375]: Info: Found H.264 encoder: h264_vaapi [vaapi]
[2025-06-11 19:32:26.375]: Debug: ------  hevc ------
[2025-06-11 19:32:26.375]: Debug: PASSED: supported
[2025-06-11 19:32:26.375]: Debug: REF_FRAMES_RESTRICT: supported
[2025-06-11 19:32:26.375]: Debug: DYNAMIC_RANGE: supported
[2025-06-11 19:32:26.375]: Debug: YUV444: unsupported
[2025-06-11 19:32:26.375]: Debug: VUI_PARAMETERS: supported
[2025-06-11 19:32:26.375]: Debug: -------------------
[2025-06-11 19:32:26.375]: Info: Found HEVC encoder: hevc_vaapi [vaapi]
[2025-06-11 19:32:26.375]: Debug: ------  av1 ------
[2025-06-11 19:32:26.375]: Debug: PASSED: supported
[2025-06-11 19:32:26.375]: Debug: REF_FRAMES_RESTRICT: supported
[2025-06-11 19:32:26.375]: Debug: DYNAMIC_RANGE: supported
[2025-06-11 19:32:26.375]: Debug: YUV444: unsupported
[2025-06-11 19:32:26.375]: Debug: VUI_PARAMETERS: unsupported
[2025-06-11 19:32:26.375]: Debug: -------------------
[2025-06-11 19:32:26.375]: Info: Found AV1 encoder: av1_vaapi [vaapi]
[2025-06-11 19:32:26.376]: Info: Adding avahi service siegfried
[2025-06-11 19:32:26.377]: Info: Configuration UI available at [https://localhost:47990]
```

**Comment by gschintgen** [comment]
> So you're seeing bitrate excursions even with the VAAPI strict bitrate enforcement option enabled?

Hmm, no, in my case it's rather the opposite as I'm seeing right now. I hope I'm not confusing matters here. But the symptoms are like described in the original post.

> Please post your logs with debug log level so we can see what rate control and VBV size was chosen by Sunshine and FFmpeg.
> 
> It would also be useful to get these logs both from [9662f05](https://github.com/LizardByte/Sunshine/commit/9662f0547f116bdd6870ec7c8ab246e95572585f) and from the latest version of Sunshine, so we can compare them.

Sure, I'll start with 9662f054 which is totally clean as far as I can tell. I'm attaching the debug log of a complete session and also a screenshot of netdata running on the host. The bitrate is stable at 80MBit/s. (19:18:00 to 19:24:00)

![Image](https://github.com/user-attachments/assets/8e299d8d-2e92-4935-949b-ceb5e07ba341)
[sunshine-9662f054-debug.log](https://github.com/user-attachments/files/20695597/sunshine-9662f054-debug.log)

**Comment by gschintgen** [comment]
And here's how every commit after the vaapi commit of 1st Nov. is behaving. Again a debug log of a whole test session and a netdata screenshot. As you can see sunshine can't even reach 80 MBit/s. The stream works for a few seconds (10?) and then it degrades and stays in a not very enjoyable state. See 19:36:00 to 19:38:00. I tested using the latest available commit (7017b8e8).

Everything is compiled from source and I verified that I have `submodule.recurse` enabled in git to ensure that I'm not mixing and matching versions. Anyway it's the same brokenness that I'm having with the latest official release build.

Oh, and thanks for all the time you spent looking into the AMD / VAAPI issues, @cgutman !

![Image](https://github.com/user-attachments/assets/56cef41c-4d09-40fd-b5a3-f034e02f6fc9)
[sunshine-7017b8e8-debug.log](https://github.com/user-attachments/files/20695840/sunshine-7017b8e8-debug.log)

**Comment by gschintgen** [comment]
And if we're at it: my client device is configured to keep monlight logs. So here's a moonlight logfile that also covers both test sessions. Unfortunately there's another session included too. But the difference between working and broken should be clear.

[moonlight-2025-06-11-1907.log](https://github.com/user-attachments/files/20695990/moonlight-2025-06-11-1907.log)

(I'm still plagued by the 1920x108**8** issue, including green bar at the bottom, but that should be unrelated? I suppose it will be fixed in time by an OS upgrade. Or I'll reluctantly go back to h264. Network bandwidth shouldn't be an issue with GBit ethernet.)

**Comment by gschintgen** [comment]
I've re-read the original post and I might indeed face a different issue after all :-/

During testing I also encountered the `Skipping FEC for abnormally large encoded frame (needed 5 FEC blocks)" messages but that was when I had the strict bitrate enforcement *disabled* (which is the default). And in that case it's not unexpected to have those unfortunate spikes.

**Comment by rikiguan** [comment]
> I encountered a similar issue: on Ubuntu 24.04, Sunshine uses significantly more bandwidth than the maximum bitrate I configured whenever there are transition animations in the GNOME interface. It seems like my bitrate settings have no effect. In some cases, this causes my Moonlight connection to freeze, although the mouse can still move. I suspect the issue lies with Wayland's rendering or refresh logic.

After my tests, it seems the issue is that when installing the .deb package directly, setting the maximum bit rate doesn't work at all. However, when installed via Flatpak, there are no issues. The problem is that Flatpak requires root privileges for auto-start. Do you have any good solutions for this? 
The version of Sunshine is the latest, and I suspect that some drivers might be missing.

**Comment by rikiguan** [comment]
> > I encountered a similar issue: on Ubuntu 24.04, Sunshine uses significantly more bandwidth than the maximum bitrate I configured whenever there are transition animations in the GNOME interface. It seems like my bitrate settings have no effect. In some cases, this causes my Moonlight connection to freeze, although the mouse can still move. I suspect the issue lies with Wayland's rendering or refresh logic.
> 
> After my tests, it seems the issue is that when installing the .deb package directly, setting the maximum bit rate doesn't work at all. However, when installed via Flatpak, there are no issues. The problem is that Flatpak requires root privileges for auto-start. Do you have any good solutions for this? The version of Sunshine is the latest, and I suspect that some drivers might be missing.

When I switch the encoder from VA-API to software, I regain control over the bitrate. This suggests the issue may lie with VA-API on Linux — possibly a limitation where bitrate control doesn't work properly in VA-API mode.

Besides, the "Strictly enforce frame bitrate limits for H.264/HEVC on AMD GPUs" didnt work

**Comment by hanneshoch3** [comment]
> [2025-07-19 21:30:29.689]: Info: --------- End of KMS monitor list ---------
[2025-07-19 21:30:29.689]: Info: Screencasting with KMS
[2025-07-19 21:30:29.689]: Info: /dev/dri/card0 -> amdgpu
[2025-07-19 21:30:29.689]: Info: Found monitor for DRM screencasting
[2025-07-19 21:30:29.689]: Info: Found connector ID [93]
[2025-07-19 21:30:29.689]: Info: Found cursor plane [76]
[2025-07-19 21:30:29.694]: Info: Creating encoder [hevc_vaapi]
[2025-07-19 21:30:29.694]: Info: Color coding: HDR (Rec. 2020 + SMPTE 2084 PQ)
[2025-07-19 21:30:29.694]: Info: Color depth: 10-bit
[2025-07-19 21:30:29.694]: Info: Color range: JPEG
[2025-07-19 21:30:29.701]: Info: vaapi vendor: Mesa Gallium driver 25.3.0-devel for AMD Radeon RX 7900 XT (radeonsi, navi31, LLVM 20.1.8, DRM 3.63, 6.15.7-1-cachyos)
[2025-07-19 21:30:29.702]: Info: Streaming bitrate is 24188000
[2025-07-19 21:30:29.702]: Info: Using normal encoding mode
[2025-07-19 21:30:29.702]: Info: Using VBR with single frame VBV size
[2025-07-19 21:30:29.709]: Info: Minimum frame time set to 8.33333ms, based on client-requested target framerate 120.
[2025-07-19 21:30:29.758]: Info: Found default monitor by name: bluez_output.F4_9D_8A_09_CD_47.1.monitor
[2025-07-19 21:30:29.775]: Info: Opus initialized: 48 kHz, 2 channels, 512 kbps (total), LOWDELAY
[2025-07-19 21:30:33.111]: Warning: Skipping FEC for abnormally large encoded frame (needed 6 FEC blocks)
[2025-07-19 21:30:33.211]: Warning: Skipping FEC for abnormally large encoded frame (needed 6 FEC blocks)
[2025-07-19 21:30:51.143]: Info: CLIENT DISCONNECTED


This is still an issue, the stutters because of bitrate overshoot happen a lot more often than the FEC error appears.

**Comment by awalende** [comment]
I'm not quite sure if my issues are related here. I also run a RDNA2 GPU (6800 XT) and KDE Plasma on Wayland. Client (Series X) and Server are wired via gigabit ethernet. I stream with 2560x1440@120fps. Streaming is done in HEVC with 60Mbit. I also limit the FPS of my Games accordingly to 120 fps. There are distinct phases where the stream is buttery smooth for a few seconds and afterwards a few seconds where I notice small stuttering.....back and forth. Usually smaller stuttering appears when I don't lock stream and game FPS together, however on Linux it's more noticable, as if a frame is here and there swallowed. I also see the warning in the logs regarding "abnormally large encoded frame". Is this issue here explaining my symptoms?

I'll definetally check out running sunshine via flatpak. Sadly I can't try using the software encoder as comparison, my Series X only shows a black screen with that setting.

**Comment by awalende** [comment]
UPDATE:
My stuttering issues from above are resolved by applying https://gitlab.freedesktop.org/drm/amd/-/issues/1500#note_1854170 and therefore had nothing to do with this issue.
However after a play session, I now notice intermittent full freezes of my stream. The logs don't show anything interesting, only "CLIENT DISCONNECTED". Then I tried a new Client, a wired Lenovo T14s. Here the freezes are a lot more frequent. First I receive the red warning to lower my bitrate and then full freeze. Using the same Host but with Windows 11 and AMF-Encoding, everything is fine.

I wasn't able to use an old build on my Arch Host like @gschintgen did, I stumble over shared library issues after building.

[sunshine.log](https://github.com/user-attachments/files/22031843/sunshine.log)

**Comment by hanneshoch3** [comment]
I was hoping yesterdays update with a ffmpeg version bump might somehow solve this, but this issue still persists just the same. Setting a minimum fps of 60 also makes no difference.

**Comment by inkatail** [comment]
its sad how this issue is literally the only thing keeping me from moving to Linux from Windows lol

**Comment by hanneshoch3** [comment]
So I noticed if I DISABLE strict bitrate and use HEVC it behaves much better. Occassionally it still freezes (until there is significant change on the screen), but overall it seems much better. The actual bitrate sent out over my NIC seems a lot more stable and way less spiky, but as I said still not perfect. I saw a MR regarding HEVC profiles, maybe this is related, as this was not the case before I think.

AV1 is still horrible and stutters like crazy

EDIT:

Is it in any way possible to add another vaapi toggle to use CBR instead of VBR (since even with enforced bitrate limits it spikes)? I wouldn't mind excessive data usage in idle scenes if it would remove all those stutters/freezes.

**Comment by gschintgen** [comment]
I reported a similar (but possibly different) issue in this previous comment here: https://github.com/LizardByte/Sunshine/issues/3817#issuecomment-2963716072 above. That was with an RDNA2 GPU (RX6650) on Ubuntu 24.04 with kisak-mesa PPA (in order to have a more recent mesa version with other fixes that I needed). A few months have passed and I'm happy to report that this particular issue has gone away. Unfortunately I can't say which change fixed it. Possibly the removal of the kisak-mesa PPA which was no longer needed. (I'm still plagued by the green line at the bottom of the screen though, when using h265 1080p)

**Comment by hanneshoch3** [comment]
I am running mesa-git on arch. While the stutters have gotten better as mentioned, they most definetely are still there. I can reliably provoke stutters by using web google earth at 40 mbit/s with 56 mbit/s max available. If you wildly move the map on earth it is smooth, but as soon as you get static content and THEN move the map again there are bitrate excursions and stutters.

**Comment by Ch4tul** [comment]
I would like to point out that:
With AMF on windows I can't reproduce the issue.

With vaapi and av1 on Linux, there is heavy packet loss on still scenes, and selecting strict bitrate controls doenst help.

With HEVC the issue doesn't happen at all (as long as strict bitrate control is disabled as well).

But that's unfortunate since av1 maintains superior quality when there are moving scenes, when it works.

Also for last, on Linux with vaapi when selecting av1 the host takes about 40ms to render a frame while on windows with amf it would take 5ms on average (1080p, 7900xtx)

**Comment by hanneshoch3** [comment]
Hey guys,
I myself have really no experience or skill in coding at all. I gave Qwen Coder Next in Code OSS a try to fix this issue and it seems to have succeeded. As far as I can tell it basically just forces CBR when strict RC buffer has been enabled. Worked right away for me (tested in google earth against the most recent unpatched git version on cachyos as before, which always provoked lags). Network stats/bandwidth seem completely steady now. I have attached the generated patch. Again, I don't have any experience in coding, but this worked for me so far. Both HEVC and AV1 work stutter- and lag free over limited bandwidth/internet connection now.

[vaapi-ratecontrol.patch](https://github.com/user-attachments/files/25462252/vaapi-ratecontrol.patch)

**Comment by inkatail** [comment]
> Hey guys, I myself have really no experience or skill in coding at all. I gave Qwen Coder Next in Code OSS a try to fix this issue and it seems to have succeeded. As far as I can tell it basically just forces CBR when strict RC buffer has been enabled. Worked right away for me (tested in google earth against the most recent unpatched git version on cachyos as before, which always provoked lags). Network stats/bandwidth seem completely steady now. I have attached the generated patch. Again, I don't have any experience in coding, but this worked for me so far. Both HEVC and AV1 work stutter- and lag free over limited bandwidth/internet connection now.
> 
> [vaapi-ratecontrol.patch](https://github.com/user-attachments/files/25462252/vaapi-ratecontrol.patch)

Can confirm this kinda works, would be good to perhaps make a pull request which would add manual RC mode choosing to VA-API, the not merged yet Vulkan encoder seems to have similiar issue except that it's missing the strict rc buffer configuration, it has RC mode choosing though.

**Comment by regalialong** [comment]
I think I'm affected by this, I'm not entirely sure. I'm on Arch using Sunshine `2026.310.23228` from lizardbyte-beta and Mesa `1:26.0.1-1` with Plasma `6.6.2`

When I alt tab to Konsole and run `journalctl -r`, or less easily reproducibly I switch to certain browser tabs, then the stream from my RX 9070 XT simply halts for +6s and I see network dropped frames spike to 60%-90% once it eventually recovers. Strict bitrate enforcement doesn't fix it.

I'm 100% certain that it's not my setup specifically because Sunshine was actually flawlessly working on my 3080 until I switched to this GPU.

I can play _Ultrakill_ (which is the best encoder stress test I can think of with lots of movements and particles) and I don't experience a single choke, this purely happens during desktop-y usage.

**Comment by regalialong** [comment]
Captured a video from the guest to show what I mean (watch the seconds on the clock in the bottom right):

https://github.com/user-attachments/assets/beda2ee0-5ee9-4863-8017-7c99372e83ad

Even watching the video manages to trigger it ^^'

**Comment by hanneshoch3** [comment]
Thinking this could be closed. I tried the Vulkan Encoder today and setting it to CBR works just as fine as my "dirty" fix. VAAPI and Vulkan with VBR show the same issues as before though.
