### ISSUE TITLE
pairing with -0 parameter STDIN not working anymore

### ISSUE THREAD

**Issue by comsyspro** [LizardByte/Sunshine#3868]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is your issue described in the documentation?

- [x] I have read the documentation

### Is your issue present in the latest beta/pre-release?

None

### Describe the Bug

i changed the code here to have a fixed pin for an automated pairing workflow - like std::string pin = "1234";
https://github.com/LizardByte/Sunshine/blob/7b873e9ea42d542312576818c6fb1a03e04ae156/src/nvhttp.cpp#L582

In earlier releases like 0.23.1 this pairing process worked fine but in the latest code it seems something has changed.

i also found this code and here you need a pin and a name and in earlier releases you only had a pin there and no name
https://github.com/LizardByte/Sunshine/blob/7b873e9ea42d542312576818c6fb1a03e04ae156/src/confighttp.cpp#L1022C7-L1023C59

so what should be changed here so that stdin will work again? (moonlight only passes a pin and can't pass a name)

### Host Operating System

Windows

### Operating System Version

Win 11

### Architecture

amd64/x86_64

### Sunshine commit or version

master branch

### Package

Windows - portable (not recommended)

### GPU Type

AMD

### GPU Model

RTX 3070

### GPU Driver/Mesa Version

latest

### Capture Method

None

### Config

```Shell

```

### Apps

```json

```

### Relevant log output

```shell
nothing
```

**Comment by ReenigneArcher** [comment]
The name is provided the web UI / rest API.

What moonlight client and version are you using? My suspicion is this actually broke from fixing out of order pairing: https://github.com/LizardByte/Sunshine/security/advisories/GHSA-3hrw-xv8h-9499

If it's an official client and updated, then perhaps this (https://github.com/LizardByte/Sunshine/blob/7b873e9ea42d542312576818c6fb1a03e04ae156/src/nvhttp.cpp#L581-L588) should have been updated with https://github.com/LizardByte/Sunshine/pull/2042

Not sure we should even support this feature through stdin anymore though. That's a legacy thing from before the web UI existed.

**Comment by comsyspro** [comment]
please let this feature with stdin in the code because i need it for an automated way to do the pairing process. i used moonlight version 6.0.1 on a windows 7 machine but normally i use moonlight 6.1.0 on win 11 or win 10. probably i should try it with moonlight 6.1.0 once again. but would it also possible to pair with a curl command on the api endpoint of the webserver? if this is possible i would send a post request with pin and name to that endpoint.

**Comment by ReenigneArcher** [comment]
> the last sunshine version i have compiled was 2024.922.10353 where the stdin was working fine

If that's the case then it has nothing to do with #2042 as this feature was already merged at that point.

**Comment by comsyspro** [comment]
i just tried it again with portable version v2025.509.184504 and when setting `sunshine.exe -0` and after entering pin moonlight shows the error message `Invalid uniqueid (Error 400)`

so if someone can look at this issue please.

another option i found for autopairing is to use the api endpoint sending a post request with pin and name. that i already have done now instead and it worked fine.

**Comment by MrAwesome** [comment]
Seeing the same behavior - when pairing with a PIN via -0, I always get `Invalid uniqueid (Error 400)` from moonlight.

**Comment by comsyspro** [comment]
instead, you can do it with an curl request to the api endpoint. you have to study a little bit the code if you wish to have an automated pairing process.

**Comment by ReenigneArcher** [comment]
Rest api works, we should still get it working through stdin or drop that option.

**Comment by MrAwesome** [comment]
(For what it's worth, my use case wasn't in automating pairing, it was in setting up Sunshine on a single personal remote host where I didn't have physical access to use the monitor. I assume that's a pretty rare workflow all things considered, but figure it merits mentioning since the stdin flag (or anything similar) does work well for the once-off case.)

Went and looked it up - for future people also finding this thread on Google and trying to figure out how to input a sunshine pin from the command line, there's a curl command listed here that should do it:
https://docs.lizardbyte.dev/projects/sunshine/latest/md_docs_2api.html#post-apipin

**Comment by derekelkins** [comment]
I believe there's supposed to be a `return` after the `getservercert` here:

https://github.com/LizardByte/Sunshine/blob/2f7657a1b0467c09defc7d092354ccf0057a0419/src/nvhttp.cpp#L586-L589

Otherwise, the code falls through but `uniqID` has been moved out so the "empty" `uniqID` fails to be found here:

https://github.com/LizardByte/Sunshine/blob/2f7657a1b0467c09defc7d092354ccf0057a0419/src/nvhttp.cpp#L605

**Comment by emsorganization** [comment]
Same problem

**Comment by MrAwesome** [comment]
I don't have the exact command handy on this computer, but I think it looks something like this on Linux, the wiki I linked above has other methods:

```bash
SUNSHINE_USER=your_sunshine_username
SUNSHINE_PASSWORD=your_sunshine_password

# If you haven't set the username and password already:
sunshine --creds "$SUNSHINE_USER" "$SUNSHINE_PASSWORD"

# Once you have the pairing request from Moonlight:
DESIRED_PIN=your_pairing_pin_code
curl -u "$SUNSHINE_USER":"$SUNSHINE_PASSWORD" -H "Content-Type: application/json" -X POST -k https://localhost:47990/api/pin -d '{"pin":"'"$DESIRED_PIN"'", "name":"whateverhostname_doesnotmatter_afaik"}'
```

You can also run that curl command from anywhere that has network access (including the port being open) to the box running Sunshine.

**Comment by appleseedexm** [comment]
Personally I think it is a common usecase to authenticate remote clients in a remote-control software. I did this via ssh multiple times and wasted a bit too much time now to get this to work again.
 
It was a very convenient feature, but at least there's a workaround. Removing the broken implementation will at least save some time for people trying to get this to work. Even if it's just a "adding clients via stdin is not supported anymore, use curl instead" with a wiki link or something when starting `sunshine -0`, thanks!

**Comment by pmp-p** [comment]
imho bug should be fixed or functionnality removed. Lost 30 or more minutes on that to be completely sure it was a regression, bothered on discord and finally found this opened issue.

**Comment by ztx-lyghters** [comment]
This bug is still present in the latest release, at least in the AppImage version.

I run the AppImage with -0 argument, try to connect with Moonlight, enter the code, press Enter, line changes, nothing happens. It just waits indefinitely. Ctrl+C produces a message "Error: Couldn't accept incoming connections: Operation canceled". So basically, the PIN isn't being actually read from stdin.

At the same time I also cannot access the web-interface, is it not accessible from localhost:47990 or 127.0.0.1:47990, it only opens on 192.168.200.100:47990, which is my IP, and it won't let me log in with "Not authorized" error.
Therefore I cannot authorize any client whatsoever.

**Comment by MrAwesome** [comment]
Which version is this? Can you run with --version?

**Comment by ztx-lyghters** [comment]
> Which version is this? Can you run with --version?

Latest available AppImage from Github releases.
Here's the --version output:
```
[2026-06-19 16:32:53.569066] [0x00007fa12bece000] [info]    config: 'vk_tune' = 3
[2026-06-19 16:32:53.569095] [0x00007fa12bece000] [info]    config: 'system_tray' =
disabled
[2026-06-19 16:32:53.569099] [0x00007fa12bece000] [info]    config: 'sw_preset' = veryfast
[2026-06-19 16:32:53.569106] [0x00007fa12bece000] [info]    config: 'wan_encryption_mode' = 2
[2026-06-19 16:32:53.569110] [0x00007fa12bece000] [info]    config: 'qp' = 20
[2026-06-19 16:32:53.569114] [0x00007fa12bece000] [info]    config: 'minimum_fps_target' = 50
[2026-06-19 16:32:53.569117] [0x00007fa12bece000] [info]    config: 'fec_percentage' = 12
[2026-06-19 16:32:53.569120] [0x00007fa12bece000] [info]    config: 'hevc_mode' = 0
[2026-06-19 16:32:53.569124] [0x00007fa12bece000] [info]    config: 'encoder' = vaapi
[2026-06-19 16:32:53.569127] [0x00007fa12bece000] [info]    config: 'av1_mode' = 0
[2026-06-19 16:32:53.569]: Info: Sunshine version: 2026.516.143833 commit: 14ffa6fdaa53f7b51512be2b3d24f3939695403c
[2026-06-19 16:32:53.569]: Info: Package Publisher: LizardByte
[2026-06-19 16:32:53.569]: Info: Publisher Website: https://app.lizardbyte.dev
[2026-06-19 16:32:53.569]: Info: Get support: https://app.lizardbyte.dev/support
[2026-06-19 16:32:53.569]: Info: config: 'av1_mode' = 0
[2026-06-19 16:32:53.569]: Info: config: 'encoder' = vaapi
[2026-06-19 16:32:53.569]: Info: config: 'hevc_mode' = 0
[2026-06-19 16:32:53.569]: Info: config: 'fec_percentage' = 12
[2026-06-19 16:32:53.569]: Info: config: 'minimum_fps_target' = 50
[2026-06-19 16:32:53.569]: Info: config: 'qp' = 20
[2026-06-19 16:32:53.569]: Info: config: 'wan_encryption_mode' = 2
[2026-06-19 16:32:53.570]: Info: config: 'sw_preset' = veryfast
[2026-06-19 16:32:53.570]: Info: config: 'system_tray' = disabled
[2026-06-19 16:32:53.570]: Info: config: 'vk_tune' = 3
```

**Comment by MrAwesome** [comment]
@ztx-lyghters I see, thanks for verifying. I think you're encountering a different bug - this bug produced the error message `Invalid uniqueid (Error 400)`, and the web interface was still accessible. I'm not near my computer for a few more days to check, but I would guess you're encountering something else. 

If it is a stdin PIN issue, you can try the curl workaround here:

https://github.com/LizardByte/Sunshine/issues/3868#issuecomment-3444777926

If that fails, it's likely something odd is going on with your networking setup on the machine where sunshine is running (or you've found a very strange bug).
