### ISSUE TITLE
Stream freezes with HAGS turned on

### ISSUE THREAD

**Issue by Puni123** [LizardByte/Sunshine#863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your issue described in the documentation?

- [X] I have read the documentation

### Is your issue present in the nightly release?

- [X] This issue is present in the nightly release

### Describe the Bug

HAGS is turned on with my 4070TI. I start sushine 0.18.
On my Shield I start moonlight and connect to sunshine to start steam big picture.

In steam big picture I start Spider-Man Miles Morales. It runs with HDR, 4K 60 Hz. First very smoothly.
Then it gets choppy and after 30 Seconds or so the picture freezes.

The sunshine server still runs, but the picture ony my TV is frozen.
The game still runs on my PC.

Without HAGs, the game doesn´t have this behaviour.
Maybe someone can replicate this with more tech knowledge than I have.

I tried to set the logs to Debug, but no error is shown in the logs.

### Expected Behavior

Should not freeze and run smoothly.

### Host Operating System

Windows

### Operating System Version

WIN 11 - 22H2 - 22621.1194

### Architecture

64bit

### Sunshine commit or version

0.18.0

### Package

Windows - portable

### GPU Type
Nvidia

### GPU Model

RTX 4070TI

### GPU Driver/Mesa Version

528.24

### Relevant log output

```Shell
[2023:01:30:12:18:16]: Info: Compiling shaders...
[2023:01:30:12:18:16]: Info: Compiled shaders
[2023:01:30:12:18:16]: Info: // Testing for available encoders, this may generate errors. You can safely ignore those errors. //
[2023:01:30:12:18:16]: Info: Trying encoder [nvenc]
[2023:01:30:12:18:16]: Info: ddprobe.exe [1] [\\.\DISPLAY1] returned: 0x00000000
[2023:01:30:12:18:16]: Info: Set GPU preference: 1
[2023:01:30:12:18:16]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:16]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:16]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:16]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:16]: Info: SDR color coding [Rec. 601]
[2023:01:30:12:18:16]: Info: Color range: [JPEG]
[2023:01:30:12:18:16]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:16]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:16]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:16]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:16]: Info: SDR color coding [Rec. 601]
[2023:01:30:12:18:16]: Info: Color range: [JPEG]
[2023:01:30:12:18:17]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:17]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:17]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:17]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:17]: Info: SDR color coding [Rec. 601]
[2023:01:30:12:18:17]: Info: Color range: [JPEG]
[2023:01:30:12:18:17]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:17]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:17]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:17]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:17]: Info: SDR color coding [Rec. 601]
[2023:01:30:12:18:17]: Info: Color range: [JPEG]
[2023:01:30:12:18:17]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:17]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:17]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:17]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:17]: Info: SDR color coding [Rec. 601]
[2023:01:30:12:18:17]: Info: Color range: [JPEG]
[2023:01:30:12:18:17]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:17]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:17]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:17]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:17]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2023:01:30:12:18:17]: Info: Color range: [JPEG]
[2023:01:30:12:18:17]: Error: Could not open codec [h264_nvenc]: Function not implemented
[2023:01:30:12:18:17]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:17]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:17]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:17]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:17]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2023:01:30:12:18:17]: Info: Color range: [JPEG]
[2023:01:30:12:18:18]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:18]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:18]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:18]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:18]: Info: SDR color coding [Rec. 601]
[2023:01:30:12:18:18]: Info: Color range: [JPEG]
[2023:01:30:12:18:18]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:18:18]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:18:18]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:18:18]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:18:18]: Info: SDR color coding [Rec. 601]
[2023:01:30:12:18:18]: Info: Color range: [JPEG]
[2023:01:30:12:18:18]: Warning: nvenc: hevc: replacing nalu prefix data
[2023:01:30:12:18:18]: Info: 
[2023:01:30:12:18:18]: Info: // Ignore any errors mentioned above, they are not relevant. //
[2023:01:30:12:18:18]: Info: 
[2023:01:30:12:18:18]: Debug: ------  h264 ------
[2023:01:30:12:18:18]: Debug: PASSED: supported
[2023:01:30:12:18:18]: Debug: REF_FRAMES_RESTRICT: supported
[2023:01:30:12:18:18]: Debug: REF_FRAMES_AUTOSELECT: supported
[2023:01:30:12:18:18]: Debug: SLICE: supported
[2023:01:30:12:18:18]: Debug: CBR: supported
[2023:01:30:12:18:18]: Debug: DYNAMIC_RANGE: unsupported
[2023:01:30:12:18:18]: Debug: VUI_PARAMETERS: supported
[2023:01:30:12:18:18]: Debug: NALU_PREFIX_5b: supported
[2023:01:30:12:18:18]: Debug: -------------------
[2023:01:30:12:18:18]: Debug: ------  hevc ------
[2023:01:30:12:18:18]: Debug: PASSED: supported
[2023:01:30:12:18:18]: Debug: REF_FRAMES_RESTRICT: supported
[2023:01:30:12:18:18]: Debug: REF_FRAMES_AUTOSELECT: supported
[2023:01:30:12:18:18]: Debug: SLICE: supported
[2023:01:30:12:18:18]: Debug: CBR: supported
[2023:01:30:12:18:18]: Debug: DYNAMIC_RANGE: supported
[2023:01:30:12:18:18]: Debug: VUI_PARAMETERS: supported
[2023:01:30:12:18:18]: Debug: NALU_PREFIX_5b: unsupported
[2023:01:30:12:18:18]: Debug: -------------------
[2023:01:30:12:18:18]: Info: Found encoder nvenc: [h264_nvenc, hevc_nvenc]
[2023:01:30:12:18:18]: Info: Configuration UI available at [https://localhost:47990]
[2023:01:30:12:18:19]: Info: Registered Sunshine mDNS service
[2023:01:30:12:19:52]: Debug: TUNNEL :: NONE
[2023:01:30:12:19:52]: Debug: METHOD :: GET
[2023:01:30:12:19:52]: Debug: DESTINATION :: /serverinfo
[2023:01:30:12:19:52]: Debug: Host -- 192.168.22.3:47989
[2023:01:30:12:19:52]: Debug: User-Agent -- Dalvik/2.1.0 (Linux; U; Android 11; SHIELD Android TV Build/RQ1A.210105.003)
[2023:01:30:12:19:52]: Debug: Accept-Encoding -- gzip
[2023:01:30:12:19:52]: Debug: Connection -- Keep-Alive
[2023:01:30:12:19:52]: Debug: X-GS-Version -- 7.1
[2023:01:30:12:19:52]: Debug: GS-Server-Id -- 12a45a63-ee0d-4faf-b8bb-cb682d50f1d6
[2023:01:30:12:19:52]: Debug:  [--] 
[2023:01:30:12:19:52]: Debug: uuid -- a82a89e5-0d3d-4950-b91a-36d9b2559a33
[2023:01:30:12:19:52]: Debug: uniqueid -- 4222150137010000210
[2023:01:30:12:19:52]: Debug:  [--] 
[2023:01:30:12:19:53]: Debug: TUNNEL :: NONE
[2023:01:30:12:19:53]: Debug: METHOD :: GET
[2023:01:30:12:19:53]: Debug: DESTINATION :: /serverinfo
[2023:01:30:12:19:53]: Debug: Host -- 192.168.22.3:47989
[2023:01:30:12:19:53]: Debug: User-Agent -- Dalvik/2.1.0 (Linux; U; Android 11; SHIELD Android TV Build/RQ1A.210105.003)
[2023:01:30:12:19:53]: Debug: Accept-Encoding -- gzip
[2023:01:30:12:19:53]: Debug: Connection -- Keep-Alive
[2023:01:30:12:19:53]: Debug: X-GS-Version -- 7.1
[2023:01:30:12:19:53]: Debug: GS-Server-Id -- 12a45a63-ee0d-4faf-b8bb-cb682d50f1d6
[2023:01:30:12:19:53]: Debug:  [--] 
[2023:01:30:12:19:53]: Debug: uuid -- cddec4e6-5638-400c-a59d-a4b92037fb40
[2023:01:30:12:19:53]: Debug: uniqueid -- 4222150137010000210
[2023:01:30:12:19:53]: Debug:  [--] 
[2023:01:30:12:19:53]: Debug: TUNNEL :: NONE
[2023:01:30:12:19:53]: Debug: METHOD :: GET
[2023:01:30:12:19:53]: Debug: DESTINATION :: /serverinfo
[2023:01:30:12:19:53]: Debug: User-Agent -- okhttp/3.12.13
[2023:01:30:12:19:53]: Debug: Accept-Encoding -- gzip
[2023:01:30:12:19:53]: Debug: Connection -- Keep-Alive
[2023:01:30:12:19:53]: Debug: Host -- 192.168.22.3:47989
[2023:01:30:12:19:53]: Debug:  [--] 
[2023:01:30:12:19:53]: Debug: uuid -- 225107fe-d7c9-4372-a3bf-df1b714264aa
[2023:01:30:12:19:53]: Debug: uniqueid -- 0123456789ABCDEF
[2023:01:30:12:19:53]: Debug:  [--] 
[2023:01:30:12:19:53]: Info: /CN=NVIDIA GameStream Client -- verified
[2023:01:30:12:19:53]: Debug: TUNNEL :: HTTPS
[2023:01:30:12:19:53]: Debug: METHOD :: GET
[2023:01:30:12:19:53]: Debug: DESTINATION :: /serverinfo
[2023:01:30:12:19:53]: Debug: User-Agent -- okhttp/3.12.13
[2023:01:30:12:19:53]: Debug: Accept-Encoding -- gzip
[2023:01:30:12:19:53]: Debug: Connection -- Keep-Alive
[2023:01:30:12:19:53]: Debug: Host -- 192.168.22.3:47984
[2023:01:30:12:19:53]: Debug:  [--] 
[2023:01:30:12:19:53]: Debug: uuid -- f72ef85e-8bbb-4fb8-9a99-3a55665f3a53
[2023:01:30:12:19:53]: Debug: uniqueid -- 0123456789ABCDEF
[2023:01:30:12:19:53]: Debug:  [--] 
[2023:01:30:12:19:55]: Info: /CN=NVIDIA GameStream Client -- verified
[2023:01:30:12:19:55]: Debug: TUNNEL :: HTTPS
[2023:01:30:12:19:55]: Debug: METHOD :: GET
[2023:01:30:12:19:55]: Debug: DESTINATION :: /serverinfo
[2023:01:30:12:19:55]: Debug: User-Agent -- okhttp/3.12.13
[2023:01:30:12:19:55]: Debug: Accept-Encoding -- gzip
[2023:01:30:12:19:55]: Debug: Connection -- Keep-Alive
[2023:01:30:12:19:55]: Debug: Host -- 192.168.22.3:47984
[2023:01:30:12:19:55]: Debug:  [--] 
[2023:01:30:12:19:55]: Debug: uuid -- d55f4a05-9064-4e72-853f-36a022a03ad7
[2023:01:30:12:19:55]: Debug: uniqueid -- 0123456789ABCDEF
[2023:01:30:12:19:55]: Debug:  [--] 
[2023:01:30:12:19:55]: Info: /CN=NVIDIA GameStream Client -- verified
[2023:01:30:12:19:55]: Debug: TUNNEL :: HTTPS
[2023:01:30:12:19:55]: Debug: METHOD :: GET
[2023:01:30:12:19:55]: Debug: DESTINATION :: /applist
[2023:01:30:12:19:55]: Debug: User-Agent -- okhttp/3.12.13
[2023:01:30:12:19:55]: Debug: Accept-Encoding -- gzip
[2023:01:30:12:19:55]: Debug: Connection -- Keep-Alive
[2023:01:30:12:19:55]: Debug: Host -- 192.168.22.3:47984
[2023:01:30:12:19:55]: Debug:  [--] 
[2023:01:30:12:19:55]: Debug: uuid -- c7f4a72f-2829-424b-bb1b-e52c7fb8c10f
[2023:01:30:12:19:55]: Debug: uniqueid -- 0123456789ABCDEF
[2023:01:30:12:19:55]: Debug:  [--] 
[2023:01:30:12:19:56]: Info: /CN=NVIDIA GameStream Client -- verified
[2023:01:30:12:19:56]: Debug: TUNNEL :: HTTPS
[2023:01:30:12:19:56]: Debug: METHOD :: GET
[2023:01:30:12:19:56]: Debug: DESTINATION :: /serverinfo
[2023:01:30:12:19:56]: Debug: User-Agent -- okhttp/3.12.13
[2023:01:30:12:19:56]: Debug: Accept-Encoding -- gzip
[2023:01:30:12:19:56]: Debug: Connection -- Keep-Alive
[2023:01:30:12:19:56]: Debug: Host -- 192.168.22.3:47984
[2023:01:30:12:19:56]: Debug:  [--] 
[2023:01:30:12:19:56]: Debug: uuid -- 54100212-9bcf-4bde-a1a9-d82d70e01ed1
[2023:01:30:12:19:56]: Debug: uniqueid -- 0123456789ABCDEF
[2023:01:30:12:19:56]: Debug:  [--] 
[2023:01:30:12:19:56]: Info: /CN=NVIDIA GameStream Client -- verified
[2023:01:30:12:19:56]: Debug: TUNNEL :: HTTPS
[2023:01:30:12:19:56]: Debug: METHOD :: GET
[2023:01:30:12:19:56]: Debug: DESTINATION :: /launch
[2023:01:30:12:19:56]: Debug: User-Agent -- okhttp/3.12.13
[2023:01:30:12:19:56]: Debug: Accept-Encoding -- gzip
[2023:01:30:12:19:56]: Debug: Connection -- Keep-Alive
[2023:01:30:12:19:56]: Debug: Host -- 192.168.22.3:47984
[2023:01:30:12:19:56]: Debug:  [--] 
[2023:01:30:12:19:56]: Debug: uuid -- aaea895e-81e9-448f-9c5e-a219eac41fb3
[2023:01:30:12:19:56]: Debug: uniqueid -- 0123456789ABCDEF
[2023:01:30:12:19:56]: Debug: gcmap -- 1
[2023:01:30:12:19:56]: Debug: remoteControllersBitmap -- 1
[2023:01:30:12:19:56]: Debug: appid -- 2093642156
[2023:01:30:12:19:56]: Debug: mode -- 3840x2160x60
[2023:01:30:12:19:56]: Debug: clientHdrCapDisplayData -- 0x0x0x0x0x0x0x0x0x0x0
[2023:01:30:12:19:56]: Debug: additionalStates -- 1
[2023:01:30:12:19:56]: Debug: rikey -- A6A17CB361C6453D76023BF120FEC100
[2023:01:30:12:19:56]: Debug: sops -- 0
[2023:01:30:12:19:56]: Debug: clientHdrCapMetaDataId -- NV_STATIC_METADATA_TYPE_1
[2023:01:30:12:19:56]: Debug: surroundAudioInfo -- 104792072
[2023:01:30:12:19:56]: Debug: rikeyid -- -352393634
[2023:01:30:12:19:56]: Debug: hdrMode -- 1
[2023:01:30:12:19:56]: Debug: clientHdrCapVersion -- 0
[2023:01:30:12:19:56]: Debug: clientHdrCapSupportedFlagsInUint32 -- 0
[2023:01:30:12:19:56]: Debug: localAudioPlayMode -- 0
[2023:01:30:12:19:56]: Debug:  [--] 
[2023:01:30:12:19:56]: Debug: Parsed executable [D:\Spiele\Steam\steam.exe] from command [D:\Spiele\Steam\steam.exe -bigpicture]
[2023:01:30:12:19:56]: Debug: Resolved executable [D:\Spiele\Steam\steam.exe] to path ["D:\Spiele\Steam\steam.exe"]
[2023:01:30:12:19:56]: Info: Spawning [D:\Spiele\Steam\steam.exe -bigpicture] in ["D:\Spiele\Steam"]
[2023:01:30:12:19:56]: Info: D:\Spiele\Steam\steam.exe -bigpicture running with PID 6640
[2023:01:30:12:19:56]: Debug: Parsed executable [steam] from command [steam steam://open/bigpicture]
[2023:01:30:12:19:56]: Error: Unable to find executable [steam]. Is it in your PATH?
[2023:01:30:12:19:56]: Info: Spawning [steam steam://open/bigpicture] in [""]
[2023:01:30:12:19:56]: Error: Failed to launch process: 2
[2023:01:30:12:19:56]: Warning: Couldn't spawn [steam steam://open/bigpicture]: System: Invalid argument
[2023:01:30:12:19:56]: Info: Executing [Desktop]
[2023:01:30:12:19:56]: Debug: handle_read(): Handle read of size: 99 bytes
[2023:01:30:12:19:56]: Debug: handle_payload(): Handle read of size: 0 bytes
[2023:01:30:12:19:56]: Debug: type [REQUEST]
[2023:01:30:12:19:56]: Debug: sequence number [1]
[2023:01:30:12:19:56]: Debug: protocol :: RTSP/1.0
[2023:01:30:12:19:56]: Debug: payload :: 
[2023:01:30:12:19:56]: Debug: command :: OPTIONS
[2023:01:30:12:19:56]: Debug: target :: rtsp://192.168.22.3:48010
[2023:01:30:12:19:56]: Debug: CSeq ::  1
[2023:01:30:12:19:56]: Debug: X-GS-ClientVersion ::  14
[2023:01:30:12:19:56]: Debug: Host ::  192.168.22.3
[2023:01:30:12:19:56]: Debug: ---Begin MessageBuffer---
OPTIONS
---End MessageBuffer---
[2023:01:30:12:19:56]: Debug: ---Begin Response---
RTSP/1.0 200 OK

CSeq: 1





---End Response---
[2023:01:30:12:19:56]: Debug: handle_read(): Handle read of size: 175 bytes
[2023:01:30:12:19:56]: Debug: handle_payload(): Handle read of size: 0 bytes
[2023:01:30:12:19:56]: Debug: type [REQUEST]
[2023:01:30:12:19:56]: Debug: sequence number [2]
[2023:01:30:12:19:56]: Debug: protocol :: RTSP/1.0
[2023:01:30:12:19:56]: Debug: payload :: 
[2023:01:30:12:19:56]: Debug: command :: DESCRIBE
[2023:01:30:12:19:56]: Debug: target :: rtsp://192.168.22.3:48010
[2023:01:30:12:19:56]: Debug: CSeq ::  2
[2023:01:30:12:19:56]: Debug: X-GS-ClientVersion ::  14
[2023:01:30:12:19:56]: Debug: Host ::  192.168.22.3
[2023:01:30:12:19:56]: Debug: Accept ::  application/sdp
[2023:01:30:12:19:56]: Debug: If-Modified-Since ::  Thu, 01 Jan 1970 00:00:00 GMT
[2023:01:30:12:19:56]: Debug: ---Begin MessageBuffer---
DESCRIBE
---End MessageBuffer---
[2023:01:30:12:19:56]: Debug: ---Begin Response---
RTSP/1.0 200 OK

CSeq: 2




sprop-parameter-sets=AAAAAU
a=fmtp:97 surround-params=21101
a=fmtp:97 surround-params=21101
a=fmtp:97 surround-params=642012453
a=fmtp:97 surround-params=660012345
a=fmtp:97 surround-params=85301245367
a=fmtp:97 surround-params=88001234567

---End Response---
[2023:01:30:12:19:56]: Debug: handle_read(): Handle read of size: 188 bytes
[2023:01:30:12:19:56]: Debug: handle_payload(): Handle read of size: 0 bytes
[2023:01:30:12:19:56]: Debug: type [REQUEST]
[2023:01:30:12:19:56]: Debug: sequence number [3]
[2023:01:30:12:19:56]: Debug: protocol :: RTSP/1.0
[2023:01:30:12:19:56]: Debug: payload :: 
[2023:01:30:12:19:56]: Debug: command :: SETUP
[2023:01:30:12:19:56]: Debug: target :: streamid=audio/0/0
[2023:01:30:12:19:56]: Debug: CSeq ::  3
[2023:01:30:12:19:56]: Debug: X-GS-ClientVersion ::  14
[2023:01:30:12:19:56]: Debug: Host ::  192.168.22.3
[2023:01:30:12:19:56]: Debug: Transport ::  unicast;X-GS-ClientPort=50000-50001
[2023:01:30:12:19:56]: Debug: If-Modified-Since ::  Thu, 01 Jan 1970 00:00:00 GMT
[2023:01:30:12:19:56]: Debug: ---Begin MessageBuffer---
SETUP
---End MessageBuffer---
[2023:01:30:12:19:56]: Debug: ---Begin Response---
RTSP/1.0 200 OK

CSeq: 3

Session: DEADBEEFCAFE;timeout = 90

Transport: server_port=48000





---End Response---
[2023:01:30:12:19:56]: Debug: handle_read(): Handle read of size: 212 bytes
[2023:01:30:12:19:56]: Debug: handle_payload(): Handle read of size: 0 bytes
[2023:01:30:12:19:56]: Debug: type [REQUEST]
[2023:01:30:12:19:56]: Debug: sequence number [4]
[2023:01:30:12:19:56]: Debug: protocol :: RTSP/1.0
[2023:01:30:12:19:56]: Debug: payload :: 
[2023:01:30:12:19:56]: Debug: command :: SETUP
[2023:01:30:12:19:56]: Debug: target :: streamid=video/0/0
[2023:01:30:12:19:56]: Debug: CSeq ::  4
[2023:01:30:12:19:56]: Debug: X-GS-ClientVersion ::  14
[2023:01:30:12:19:56]: Debug: Host ::  192.168.22.3
[2023:01:30:12:19:56]: Debug: Session ::   DEADBEEFCAFE
[2023:01:30:12:19:56]: Debug: Transport ::  unicast;X-GS-ClientPort=50000-50001
[2023:01:30:12:19:56]: Debug: If-Modified-Since ::  Thu, 01 Jan 1970 00:00:00 GMT
[2023:01:30:12:19:56]: Debug: ---Begin MessageBuffer---
SETUP
---End MessageBuffer---
[2023:01:30:12:19:56]: Debug: ---Begin Response---
RTSP/1.0 200 OK

CSeq: 4

Session: DEADBEEFCAFE;timeout = 90

Transport: server_port=47998





---End Response---
[2023:01:30:12:19:56]: Debug: handle_read(): Handle read of size: 215 bytes
[2023:01:30:12:19:56]: Debug: handle_payload(): Handle read of size: 0 bytes
[2023:01:30:12:19:56]: Debug: type [REQUEST]
[2023:01:30:12:19:56]: Debug: sequence number [5]
[2023:01:30:12:19:56]: Debug: protocol :: RTSP/1.0
[2023:01:30:12:19:56]: Debug: payload :: 
[2023:01:30:12:19:56]: Debug: command :: SETUP
[2023:01:30:12:19:56]: Debug: target :: streamid=control/13/0
[2023:01:30:12:19:56]: Debug: CSeq ::  5
[2023:01:30:12:19:56]: Debug: X-GS-ClientVersion ::  14
[2023:01:30:12:19:56]: Debug: Host ::  192.168.22.3
[2023:01:30:12:19:56]: Debug: Session ::   DEADBEEFCAFE
[2023:01:30:12:19:56]: Debug: Transport ::  unicast;X-GS-ClientPort=50000-50001
[2023:01:30:12:19:56]: Debug: If-Modified-Since ::  Thu, 01 Jan 1970 00:00:00 GMT
[2023:01:30:12:19:56]: Debug: ---Begin MessageBuffer---
SETUP
---End MessageBuffer---
[2023:01:30:12:19:56]: Debug: ---Begin Response---
RTSP/1.0 200 OK

CSeq: 5

Session: DEADBEEFCAFE;timeout = 90

Transport: server_port=47999





---End Response---
[2023:01:30:12:19:56]: Debug: handle_read(): Handle read of size: 1060 bytes
[2023:01:30:12:19:56]: Debug: handle_payload(): Handle read of size: 887 bytes
[2023:01:30:12:19:56]: Debug: Found Content-Length:  1352 bytes
[2023:01:30:12:19:56]: Debug: handle_payload(): Handle read of size: 465 bytes
[2023:01:30:12:19:56]: Debug: Found Content-Length:  1352 bytes
[2023:01:30:12:19:56]: Debug: type [REQUEST]
[2023:01:30:12:19:56]: Debug: sequence number [6]
[2023:01:30:12:19:56]: Debug: protocol :: RTSP/1.0
[2023:01:30:12:19:56]: Debug: payload :: v=0

o=android 0 14 IN IPv4 192.168.22.3

s=NVIDIA Streaming Client

a=x-nv-video[0].clientViewportWd:3840 

a=x-nv-video[0].clientViewportHt:2160 

a=x-nv-video[0].maxFPS:60 

a=x-nv-video[0].packetSize:1392 

a=x-nv-video[0].rateControlMode:4 

a=x-nv-video[0].timeoutLengthMs:7000 

a=x-nv-video[0].framesWithInvalidRefThreshold:0 

a=x-nv-video[0].initialBitrateKbps:60000 

a=x-nv-video[0].initialPeakBitrateKbps:60000 

a=x-nv-vqos[0].bw.minimumBitrateKbps:60000 

a=x-nv-vqos[0].bw.maximumBitrateKbps:60000 

a=x-nv-vqos[0].fec.enable:1 

a=x-nv-vqos[0].videoQualityScoreUpdateTime:5000 

a=x-nv-vqos[0].qosTrafficType:5 

a=x-nv-aqos.qosTrafficType:4 

a=x-nv-general.featureFlags:167 

a=x-nv-general.useReliableUdp:13 

a=x-nv-vqos[0].fec.minRequiredFecPackets:2 

a=x-nv-vqos[0].bllFec.enable:0 

a=x-nv-vqos[0].drc.enable:0 

a=x-nv-general.enableRecoveryMode:0 

a=x-nv-video[0].videoEncoderSlicesPerFrame:1 

a=x-nv-clientSupportHevc:1 

a=x-nv-vqos[0].bitStreamFormat:1 

a=x-nv-video[0].dynamicRangeMode:1 

a=x-nv-video[0].maxNumReferenceFrames:1 

a=x-nv-video[0].clientRefreshRateX100:6000 

a=x-nv-audio.surround.numChannels:8 

a=x-nv-audio.surround.channelMask:1599 

a=x-nv-audio.surround.enable:1 

a=x-nv-audio.surround.AudioQuality:1 

a=x-nv-aqos.packetDuration:5 

a=x-nv-video[0].encoderCscMode:2 

t=0 0

m=video 47998  

[2023:01:30:12:19:56]: Debug: command :: ANNOUNCE
[2023:01:30:12:19:56]: Debug: target :: streamid=control/13/0
[2023:01:30:12:19:56]: Debug: CSeq ::  6
[2023:01:30:12:19:56]: Debug: X-GS-ClientVersion ::  14
[2023:01:30:12:19:56]: Debug: Host ::  192.168.22.3
[2023:01:30:12:19:56]: Debug: Session ::   DEADBEEFCAFE
[2023:01:30:12:19:56]: Debug: Content-type ::  application/sdp
[2023:01:30:12:19:56]: Debug: Content-length ::  1352
[2023:01:30:12:19:56]: Debug: ---Begin MessageBuffer---
ANNOUNCE
---End MessageBuffer---
[2023:01:30:12:19:56]: Debug: ---Begin Response---
RTSP/1.0 200 OK

CSeq: 6





---End Response---
[2023:01:30:12:19:56]: Debug: handle_read(): Handle read of size: 96 bytes
[2023:01:30:12:19:56]: Debug: handle_payload(): Handle read of size: 0 bytes
[2023:01:30:12:19:56]: Debug: type [REQUEST]
[2023:01:30:12:19:56]: Debug: sequence number [7]
[2023:01:30:12:19:56]: Debug: protocol :: RTSP/1.0
[2023:01:30:12:19:56]: Debug: payload :: 
[2023:01:30:12:19:56]: Debug: command :: PLAY
[2023:01:30:12:19:56]: Debug: target :: /
[2023:01:30:12:19:56]: Debug: CSeq ::  7
[2023:01:30:12:19:56]: Debug: X-GS-ClientVersion ::  14
[2023:01:30:12:19:56]: Debug: Host ::  192.168.22.3
[2023:01:30:12:19:56]: Debug: Session ::   DEADBEEFCAFE
[2023:01:30:12:19:56]: Debug: ---Begin MessageBuffer---
PLAY
---End MessageBuffer---
[2023:01:30:12:19:56]: Debug: ---Begin Response---
RTSP/1.0 200 OK

CSeq: 7





---End Response---
[2023:01:30:12:19:56]: Info: CLIENT CONNECTED
[2023:01:30:12:19:56]: Debug: type [IDX_REQUEST_IDR_FRAME]
[2023:01:30:12:19:56]: Debug: type [IDX_START_B]
[2023:01:30:12:19:56]: Debug: RAISE: 192.168.55.2:52940 :: VIDEO
[2023:01:30:12:19:56]: Debug: Received ping from 192.168.55.2:52940 [474E4950]
[2023:01:30:12:19:56]: Debug: Start capturing Video
[2023:01:30:12:19:56]: Debug: Detecting monitors...
[2023:01:30:12:19:56]: Debug: 
====== ADAPTER =====
Device Name      : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID : 0x000010DE
Device Device ID : 0x00002782
Device Video Mem : 12010 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 8152 MiB

    ====== OUTPUT ======
[2023:01:30:12:19:56]: Debug:     Output Name       : \\.\DISPLAY1
    AttachedToDesktop : yes
    Resolution        : 3440x1440

[2023:01:30:12:19:56]: Debug:     Output Name       : \\.\DISPLAY2
    AttachedToDesktop : yes
    Resolution        : 1920x1080

[2023:01:30:12:19:56]: Debug: 
====== ADAPTER =====
Device Name      : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID : 0x000010DE
Device Device ID : 0x00002782
Device Video Mem : 12010 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 8152 MiB

    ====== OUTPUT ======
[2023:01:30:12:19:56]: Debug: 
====== ADAPTER =====
Device Name      : Microsoft Basic Render Driver
Device Vendor ID : 0x00001414
Device Device ID : 0x0000008C
Device Video Mem : 0 MiB
Device Sys Mem   : 0 MiB
Share Sys Mem    : 8152 MiB

    ====== OUTPUT ======
[2023:01:30:12:19:56]: Debug: --begin relative mouse move packet--
deltaX [1]
deltaY [1]
--end relative mouse move packet--
[2023:01:30:12:19:56]: Debug: --begin relative mouse move packet--
deltaX [-1]
deltaY [-1]
--end relative mouse move packet--
[2023:01:30:12:19:56]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3440x1440
Offset             : 0x0
Virtual Desktop    : 5360x1440
[2023:01:30:12:19:56]: Info: Desktop resolution [3440x1440]
[2023:01:30:12:19:56]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:19:56]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 8
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:19:56]: Info: Capture format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:19:56]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2023:01:30:12:19:56]: Info: Color range: [MPEG]
[2023:01:30:12:19:56]: Debug: Sent HDR mode: true
[2023:01:30:12:19:56]: Debug: RAISE: 192.168.55.2:41728 :: AUDIO
[2023:01:30:12:19:56]: Debug: Received ping from 192.168.55.2:41728 [474E4950]
[2023:01:30:12:19:56]: Debug: Start capturing Audio
[2023:01:30:12:19:57]: Debug: Stereo: supported
[2023:01:30:12:19:57]: Debug: Surround 5.1: supported
[2023:01:30:12:19:57]: Debug: Surround 7.1: supported
[2023:01:30:12:19:57]: Debug: Stereo: supported
[2023:01:30:12:19:57]: Debug: Surround 5.1: supported
[2023:01:30:12:19:57]: Debug: Surround 7.1: supported
[2023:01:30:12:19:57]: Debug: Skipping audio format [Stereo] with channel count [2 != 8]
[2023:01:30:12:19:57]: Debug: Skipping audio format [Surround 5.1] with channel count [6 != 8]
[2023:01:30:12:19:57]: Debug: Trying audio format [Surround 7.1]
[2023:01:30:12:19:57]: Debug: Found audio format [Surround 7.1]
[2023:01:30:12:20:04]: Debug: largeMotor: 0
smallMotor: 0
[2023:01:30:12:20:04]: Debug: largeMotor: 0
smallMotor: 0
[2023:01:30:12:20:04]: Debug: largeMotor: 0
smallMotor: 0
[2023:01:30:12:20:04]: Debug: Send gamepadnr [0] with lowfreq [0] and highfreq [0]
[2023:01:30:12:20:04]: Debug: Send gamepadnr [0] with lowfreq [0] and highfreq [0]
[2023:01:30:12:20:04]: Debug: Send gamepadnr [0] with lowfreq [0] and highfreq [0]
[2023:01:30:12:20:05]: Debug: largeMotor: 0
smallMotor: 0
[2023:01:30:12:20:05]: Debug: Send gamepadnr [0] with lowfreq [0] and highfreq [0]
[2023:01:30:12:20:05]: Debug: largeMotor: 0
smallMotor: 0
[2023:01:30:12:20:05]: Debug: Send gamepadnr [0] with lowfreq [0] and highfreq [0]
[2023:01:30:12:20:12]: Info: 
Device Description : NVIDIA GeForce RTX 4070 Ti
Device Vendor ID   : 0x000010DE
Device Device ID   : 0x00002782
Device Video Mem   : 12010 MiB
Device Sys Mem     : 0 MiB
Share Sys Mem      : 8152 MiB
Feature Level      : 0x0000B100
Capture size       : 3840x2160
Offset             : 0x0
Virtual Desktop    : 5760x2160
[2023:01:30:12:20:12]: Info: Desktop resolution [3840x2160]
[2023:01:30:12:20:12]: Info: Desktop format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:20:12]: Info: 
Colorspace         : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020
Bits Per Color     : 10
Red Primary        : [0.665037,0.313476]
Green Primary      : [0.275389,0.636723]
Blue Primary       : [0.140622,0.0634747]
White Point        : [0.312498,0.328124]
Min Luminance      : 0 nits
Max Luminance      : 820 nits
Max Full Luminance : 820 nits
[2023:01:30:12:20:13]: Info: Capture format [DXGI_FORMAT_R16G16B16A16_FLOAT]
[2023:01:30:12:20:13]: Info: HDR color coding [Rec. 2020 + SMPTE 2084 PQ]
[2023:01:30:12:20:13]: Info: Color range: [MPEG]
[2023:01:30:12:20:13]: Debug: Sent HDR mode: true
[2023:01:30:12:20:38]: Debug: largeMotor: 0
smallMotor: 202
[2023:01:30:12:20:38]: Debug: largeMotor: 80
smallMotor: 202
[2023:01:30:12:20:38]: Debug: largeMotor: 58
smallMotor: 202
[2023:01:30:12:20:38]: Debug: largeMotor: 27
smallMotor: 159
[2023:01:30:12:20:38]: Debug: Send gamepadnr [0] with lowfreq [51712] and highfreq [0]
[2023:01:30:12:20:38]: Debug: Send gamepadnr [0] with lowfreq [51712] and highfreq [20480]
[2023:01:30:12:20:38]: Debug: Send gamepadnr [0] with lowfreq [51712] and highfreq [14848]
[2023:01:30:12:20:38]: Debug: Send gamepadnr [0] with lowfreq [40704] and highfreq [6912]
[2023:01:30:12:20:38]: Debug: largeMotor: 23
smallMotor: 142
[2023:01:30:12:20:38]: Debug: largeMotor: 20
smallMotor: 125
[2023:01:30:12:20:38]: Debug: largeMotor: 13
smallMotor: 91
[2023:01:30:12:20:38]: Debug: Send gamepadnr [0] with lowfreq [36352] and highfreq [5888]
[2023:01:30:12:20:38]: Debug: Send gamepadnr [0] with lowfreq [32000] and highfreq [5120]
[2023:01:30:12:20:38]: Debug: Send gamepadnr [0] with lowfreq [23296] and highfreq [3328]
[2023:01:30:12:20:38]: Debug: largeMotor: 7
smallMotor: 83
[2023:01:30:12:20:38]: Debug: largeMotor: 2
smallMotor: 65
[2023:01:30:12:20:38]: Debug: largeMotor: 0
smallMotor: 46
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [21248] and highfreq [1792]
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [16640] and highfreq [512]
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [11776] and highfreq [0]
[2023:01:30:12:20:39]: Debug: largeMotor: 42
smallMotor: 44
[2023:01:30:12:20:39]: Debug: largeMotor: 0
smallMotor: 0
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [11264] and highfreq [10752]
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [0] and highfreq [0]
[2023:01:30:12:20:39]: Debug: largeMotor: 0
smallMotor: 202
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [51712] and highfreq [0]
[2023:01:30:12:20:39]: Debug: largeMotor: 0
smallMotor: 176
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [45056] and highfreq [0]
[2023:01:30:12:20:39]: Debug: largeMotor: 0
smallMotor: 142
[2023:01:30:12:20:39]: Debug: largeMotor: 0
smallMotor: 91
[2023:01:30:12:20:39]: Debug: largeMotor: 0
smallMotor: 57
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [36352] and highfreq [0]
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [23296] and highfreq [0]
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [14592] and highfreq [0]
[2023:01:30:12:20:39]: Debug: largeMotor: 0
smallMotor: 23
[2023:01:30:12:20:39]: Debug: largeMotor: 0
smallMotor: 0
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [5888] and highfreq [0]
[2023:01:30:12:20:39]: Debug: Send gamepadnr [0] with lowfreq [0] and highfreq [0]
[2023:01:30:12:20:40]: Debug: largeMotor: 47
smallMotor: 48
[2023:01:30:12:20:40]: Debug: Send gamepadnr [0] with lowfreq [12288] and highfreq [12032]
[2023:01:30:12:20:40]: Debug: largeMotor: 50
smallMotor: 50
[2023:01:30:12:20:40]: Debug: Send gamepadnr [0] with lowfreq [12800] and highfreq [12800]
[2023:01:30:12:20:41]: Debug: largeMotor: 32
smallMotor: 37
[2023:01:30:12:20:41]: Debug: largeMotor: 34
smallMotor: 34
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [9472] and highfreq [8192]
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [8704] and highfreq [8704]
[2023:01:30:12:20:41]: Debug: largeMotor: 31
smallMotor: 30
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [7680] and highfreq [7936]
[2023:01:30:12:20:41]: Debug: largeMotor: 26
smallMotor: 23
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [5888] and highfreq [6656]
[2023:01:30:12:20:41]: Debug: largeMotor: 53
smallMotor: 53
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [13568] and highfreq [13568]
[2023:01:30:12:20:41]: Debug: largeMotor: 31
smallMotor: 25
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [6400] and highfreq [7936]
[2023:01:30:12:20:41]: Debug: largeMotor: 37
smallMotor: 38
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [9728] and highfreq [9472]
[2023:01:30:12:20:41]: Debug: largeMotor: 5
smallMotor: 5
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [1280] and highfreq [1280]
[2023:01:30:12:20:41]: Debug: largeMotor: 3
smallMotor: 2
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [512] and highfreq [768]
[2023:01:30:12:20:41]: Debug: largeMotor: 9
smallMotor: 9
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [2304] and highfreq [2304]
[2023:01:30:12:20:41]: Debug: largeMotor: 14
smallMotor: 14
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [3584] and highfreq [3584]
[2023:01:30:12:20:41]: Debug: largeMotor: 23
smallMotor: 23
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [5888] and highfreq [5888]
[2023:01:30:12:20:41]: Debug: largeMotor: 28
smallMotor: 28
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [7168] and highfreq [7168]
[2023:01:30:12:20:41]: Debug: largeMotor: 27
smallMotor: 27
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [6912] and highfreq [6912]
[2023:01:30:12:20:41]: Debug: largeMotor: 29
smallMotor: 29
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [7424] and highfreq [7424]
[2023:01:30:12:20:41]: Debug: largeMotor: 34
smallMotor: 34
[2023:01:30:12:20:41]: Debug: largeMotor: 35
smallMotor: 35
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [8704] and highfreq [8704]
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [8960] and highfreq [8960]
[2023:01:30:12:20:41]: Debug: largeMotor: 43
smallMotor: 43
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [11008] and highfreq [11008]
[2023:01:30:12:20:41]: Debug: largeMotor: 38
smallMotor: 38
[2023:01:30:12:20:41]: Debug: Send gamepadnr [0] with lowfreq [9728] and highfreq [9728]
[2023:01:30:12:20:41]: Debug: largeMotor: 37
smallMotor: 37
[2023:01:30:12:20:41]: Debug: largeMotor: 36
smallMotor: 37
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [9472] and highfreq [9472]
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [9472] and highfreq [9216]
[2023:01:30:12:20:42]: Debug: largeMotor: 42
smallMotor: 43
[2023:01:30:12:20:42]: Debug: largeMotor: 40
smallMotor: 40
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [11008] and highfreq [10752]
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [10240] and highfreq [10240]
[2023:01:30:12:20:42]: Debug: largeMotor: 28
smallMotor: 29
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [7424] and highfreq [7168]
[2023:01:30:12:20:42]: Debug: largeMotor: 24
smallMotor: 25
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [6400] and highfreq [6144]
[2023:01:30:12:20:42]: Debug: largeMotor: 25
smallMotor: 26
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [6656] and highfreq [6400]
[2023:01:30:12:20:42]: Debug: largeMotor: 27
smallMotor: 28
[2023:01:30:12:20:42]: Debug: largeMotor: 34
smallMotor: 35
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [7168] and highfreq [6912]
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [8960] and highfreq [8704]
[2023:01:30:12:20:42]: Debug: largeMotor: 30
smallMotor: 30
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [7680] and highfreq [7680]
[2023:01:30:12:20:42]: Debug: largeMotor: 34
smallMotor: 34
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [8704] and highfreq [8704]
[2023:01:30:12:20:42]: Debug: largeMotor: 1
smallMotor: 1
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [256] and highfreq [256]
[2023:01:30:12:20:42]: Debug: largeMotor: 0
smallMotor: 0
[2023:01:30:12:20:42]: Debug: Send gamepadnr [0] with lowfreq [0] and highfreq [0]
[2023:01:30:12:20:43]: Debug: largeMotor: 47
smallMotor: 48
[2023:01:30:12:20:43]: Debug: Send gamepadnr [0] with lowfreq [12288] and highfreq [12032]
[2023:01:30:12:20:43]: Debug: largeMotor: 50
smallMotor: 50
[2023:01:30:12:20:43]: Debug: Send gamepadnr [0] with lowfreq [12800] and highfreq [12800]
[2023:01:30:12:20:43]: Debug: largeMotor: 31
smallMotor: 29
[2023:01:30:12:20:43]: Debug: Send gamepadnr [0] with lowfreq [7424] and highfreq [7936]
[2023:01:30:12:20:43]: Debug: largeMotor: 34
smallMotor: 34
[2023:01:30:12:20:43]: Debug: Send gamepadnr [0] with lowfreq [8704] and highfreq [8704]
[2023:01:30:12:20:43]: Debug: largeMotor: 38
smallMotor: 39
[2023:01:30:12:20:43]: Debug: Send gamepadnr [0] with lowfreq [9984] and highfreq [9728]
[2023:01:30:12:20:44]: Debug: largeMotor: 30
smallMotor: 29
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [7424] and highfreq [7680]
[2023:01:30:12:20:44]: Debug: largeMotor: 56
smallMotor: 57
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [14592] and highfreq [14336]
[2023:01:30:12:20:44]: Debug: largeMotor: 33
smallMotor: 34
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [8704] and highfreq [8448]
[2023:01:30:12:20:44]: Debug: largeMotor: 46
smallMotor: 54
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [13824] and highfreq [11776]
[2023:01:30:12:20:44]: Debug: largeMotor: 5
smallMotor: 5
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [1280] and highfreq [1280]
[2023:01:30:12:20:44]: Debug: largeMotor: 3
smallMotor: 2
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [512] and highfreq [768]
[2023:01:30:12:20:44]: Debug: largeMotor: 6
smallMotor: 6
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [1536] and highfreq [1536]
[2023:01:30:12:20:44]: Debug: largeMotor: 14
smallMotor: 14
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [3584] and highfreq [3584]
[2023:01:30:12:20:44]: Debug: largeMotor: 20
smallMotor: 20
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [5120] and highfreq [5120]
[2023:01:30:12:20:44]: Debug: largeMotor: 25
smallMotor: 25
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [6400] and highfreq [6400]
[2023:01:30:12:20:44]: Debug: largeMotor: 28
smallMotor: 28
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [7168] and highfreq [7168]
[2023:01:30:12:20:44]: Debug: largeMotor: 31
smallMotor: 31
[2023:01:30:12:20:44]: Debug: Send gamepadnr [0] with lowfreq [7936] and highfreq [7936]
[2023:01:30:12:20:44]: Debug: largeMotor: 32
smallMotor: 32
```

**Comment by Smellbourne** [comment]
I think this is somewhat a known issue. If you google hardware accelerated scheduling moonlight there are people complaining about it for a while. A shame though, since apparently DLSS3 requires it on...

**Comment by Puni123** [comment]
Yes, i am aware of that. I´ve also found some forum, where some said, that this had also been a problem with Gamestream, but it was solved for some people. I´m not sure if this is something sunshine can solve, or if it is a moonlight issue. Just wanted to raise it so maybe someone with deep knowledge could take a look. Thx.

**Comment by comienzo2093** [comment]
I am using rtx3070 and the problem was solved after completely deleting and reinstalling the graphics driver with ddu. Prior to the fix, streaming would intermittently completely freeze (on the client) with HAGS turned on. Hope this helps.

**Comment by Puni123** [comment]
I just uninstalled the driver via DDU and did a fresh driver install - didn´t solve the problem.

**Comment by justinglavin** [comment]
I'm experiencing the same issue as well. 
OS Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000
GPU RTX 4070Ti

I've uninstalled drivers with DDU and done a fresh install. The freezes usually happen when the screen is transitioning from a cut scene to gameplay or visa versa. The performance improvements from DLSS3 which requires HAGS are immense and really make the difference when streaming a newer title

**Comment by SerAlbi** [comment]
I also have this issue, the problem is that Hogwarts Legacy basically requires HAGS to be on, otherwise the framerate dips are so strong that the game is basically unplayable... Is this issue related to the encoder or anything else? Is there a way it can be patched? The issue is not present in the "stock" gamestream from nvidia

**Comment by denghongcai** [comment]
have the same issue. and not reproduced with GFE.

**Comment by Puni123** [comment]
The problem seems to be game related - i just played Returnal for a few hours with HAGS turned on without any problems. Launching Spiderman Miles Morales and the stream freezes after 10-20 seconds - as initially described.

**Comment by Sephodious** [comment]
Same issue, multiple different games.  It happened sometimes with Gamestream but stopped eventually.  Now with sunshine its reliably happening.

**Comment by Nonary** [comment]
HAGS does not freeze streams anymore this has been fixed in the most recent NVIDIA drivers.

The real cause of this issue is actually #1031

**Comment by SerAlbi** [comment]
> HAGS does not freeze streams anymore this has been fixed in the most recent NVIDIA drivers.
> 
> The real cause of this issue is actually #1031
> 
> Also just streaming in HDR alone (while 4k) can actually consume 800mb-1gb of additional VRAM compared to SDR stream. So if you want to fix this issue for now, turn down texture resolution and anything that might impact VRAM.

This is actually a very good hypothesis, but I'm currently playing at ultra 4k with something like 15gb of vram used and haven't had any freeze since i turned hags off.
Maybe it could be something related to high vram usage and HAGS on?
I recently installed Ascendio mod for hogwarts legacy and my vram usage is now around 11Gb so i could test turning hags back on just to see if the problem comes back

**Comment by SerAlbi** [comment]
Ok i've tested the game with HAGS turned on and the Ascendio mod that lowers the vram usage, and indeed the stream do not freeze anymore. So regarding the issue #1031 the freezes seems related to having BOTH, high VRAM usage and HAGS turned on.
Hope this was helpful :)

**Comment by Puni123** [comment]
I´m gonna test this too this weekend with Spiderman Miles Morales...

**Comment by Nonary** [comment]
> Ok i've tested the game with HAGS turned on and the Ascendio mod that lowers the vram usage, and indeed the stream do not freeze anymore. So regarding the issue #1031 the freezes seems related to having BOTH, high VRAM usage and HAGS turned on. Hope this was helpful :)

We've had reports that the freeze happens the exact same with HAGS on and off, no difference.

**Comment by SerAlbi** [comment]
> We've had reports that the freeze happens the exact same with HAGS on and off, no difference.

Mmmh, that's strange. I also tested with HAGS on and Hogwars Legacy Ascendio mod OFF (So that the VRAM use was insane) and it froze often. On the opposite side, turning HAGS off, the stream does NOT freeze for me even with high VRAM usage.

I have 16GB VRAM and 32GB RAM, when i say high VRAM usage i mean so high that the vram was actually swapping to paged, something like 20GB VRAM used.

The only thing that rarely happens even with HAGS off and 'reasonable' VRAM usage is that the pc completely froze like 3 or 4 times, and the display (on the pc side) only showed a distorted image of the desktop (it looked like an extremely 'posterized' screenshot of the desktop). The only way to recover was to hard reset.

Maybe this is a new and different issue?

**Comment by Sephodious** [comment]
So for me ever since turning hags off I haven't had a single freeze. However I updated something and it defaulted hags back to on and I only knew it was back on because my stream froze about 20 minutes in. I haven't tried with it in since the updated GPU drivers in a few weeks ago I can't attest to whether it's fixed or not. I'll try it again soon and report back.

**Comment by Sephodious** [comment]
Back to report that HAGS is disabled and the stream is still freezing. (Also slightly unrelated, with newest version I am getting "Connection was terminated" every time I open playnite from moonlight.  Tried service and window, admin and not admin, can't seem to fix it.  Older version doesn't do it, but freezes with HAGS turned off)

I was able to bypass this by waiting until the stream freezes, then going back to moonlight and running Desktop instead of playnite.  Since the stream froze, I'm still in game and it picks right back up where it left off and doesn't seem to freeze after that.  So until this is fixed, try launching Desktop once the stream freezes and see if that helps.

**Comment by Nonary** [comment]
> Back to report that HAGS is disabled and the stream is still freezing. (Also slightly unrelated, with newest version I am getting "Connection was terminated" every time I open playnite from moonlight.  Tried service and window, admin and not admin, can't seem to fix it.  Older version doesn't do it, but freezes with HAGS turned off)
> 
> 
> 
> I was able to bypass this by waiting until the stream freezes, then going back to moonlight and running Desktop instead of playnite.  Since the stream froze, I'm still in game and it picks right back up where it left off and doesn't seem to freeze after that.  So until this is fixed, try launching Desktop once the stream freezes and see if that helps.

As mentioned earlier in this issue, HAGS does not freeze streams anymore. There is no need to disable it anymore. 

As for your issue please set log level to debug, replicate the issue and then upload the logs here for us to review.

**Comment by Sephodious** [comment]
> 

I'll post the log after I stream and it freezes again.

**Comment by Puni123** [comment]
Hi,
the problem when the stream freezes with HAGs turned on is still present.
I can easily reproduce it with Miles Morales Spiderman und Returnal - Stream runs excellent for some minutes, but then the picture freezes. Sound is still getting streamed and i can hear that inputs from my controller are still being transmitted.

With HAGs turned off there is no problem of any kind, i can play for hours without any problem.
The logs don´t show any specific error.

Is anyone able to try returnal or miles morales with HAGs on and off to see if the same problem occours.
HAGs must be doing something in a way the stream gets interrupted, but only concerning the picture.

I know that there are some threads, which say HAGs isn´t a problem anymore, but it seems there is still some problem connect to it.

Best regards
Puni

**Comment by Nonary** [comment]
> Hi, the problem when the stream freezes with HAGs turned on is still present. I can easily reproduce it with Miles Morales Spiderman und Returnal - Stream runs excellent for some minutes, but then the picture freezes. Sound is still getting streamed and i can hear that inputs from my controller are still being transmitted.
> 
> With HAGs turned off there is no problem of any kind, i can play for hours without any problem. The logs don´t show any specific error.
> 
> Is anyone able to try returnal or miles morales with HAGs on and off to see if the same problem occours. HAGs must be doing something in a way the stream gets interrupted, but only concerning the picture.
> 
> I know that there are some threads, which say HAGs isn´t a problem anymore, but it seems there is still some problem connect to it.
> 
> Best regards Puni

Update your video card drivers

**Comment by Puni123** [comment]
Hi, i´m already on 535.98 - already did DDU with windows safe mode - the problem persists.
Therefore it would be interesting if somebody tried returnal or miles morales with HAGs on.

Regards
Puni

**Comment by Nonary** [comment]
> Hi, i´m already on 535.98 - already did DDU with windows safe mode - the problem persists. Therefore it would be interesting if somebody tried returnal or miles morales with HAGs on.
> 
> Regards Puni

Are you on the latest windows updates? This problem has been solved for months now. I’ve personally tested over 500 hours of HAGS with zero freezes. We’ve also seen a significant drop in discord about freezing issues since it was fixed.

the only freezing issue left is VRAM utilization, if it is near 100% it will freeze sunshine

**Comment by Puni123** [comment]
Hi, yes everything is update to date as can be. I´ve watched the VRAM utiliziation and with returnal and miles morales it doesnt ever fill my vram. Besides that without HAGs it runs without a problem. Not sure how i could assist in finding out what the problem is, because the Logs in Sunshine don´t show a particular problem.

Best regards
Dieter

**Comment by cgutman** [comment]
Fixed by https://github.com/LizardByte/Sunshine/commit/6dfe56518cb8295e74e3e4aef0bc771a3c333c1e

**Comment by Nonary** [comment]
> Fixed by [6dfe565](https://github.com/LizardByte/Sunshine/commit/6dfe56518cb8295e74e3e4aef0bc771a3c333c1e)
To clarify, the VRAM freeze has been fixed right? HAGS freezing has been fixed since the driver update in Feb

**Comment by noahtallen** [comment]
I was running into this issue in Jedi Survivor, so I installed the current nightly (`0.20.0.b00d7af36929f70cdb887dc0adba98b1110a503e`) to try to fix it. Unfortunately, I think this is still a problem. (I couldn't find any documentation on how to install the latest nightly, so I installed the artifact from the latest commit in the nightly branch.)

I'm streaming from Sunshine to Moonlight on the Steam Deck, which plays the Sunshine stream on my TV. I currently have the stream set to 4k@60fps (150Mbps bitrate) in Moonlight, partly because my TV and network support it, and partly to test the limits of streaming to my TV.

I'm still very early game, and the freeze occurred pretty quickly in the tutorial, when it tells you how to do a mid-air double jump. After installing the nightly, the freeze occurred right after meeting your initial companion, where there is a rope you can cut to open a shortcut. I also experienced the freeze when opening the mapa

At this point, I tried lowering some settings (running 1440p in-game with DLSS disabled, and a 1440p 100Mbps stream from Moonlight). I seemed to get somewhat further in the game, but I ultimately still experienced the freeze at least two more times in the initial mission before I gave up playing through Sunshine.

The biggest issue IMO is that Sunshine cannot recover from this issue until you quit out of the game, meaning you lose progress in the game unless you decide to continue to the next checkpoint back on your PC.

In terms of how to reproduce, play a new game of Jedi Survivor through starting tutorial mission for like 30min on high settings and it'll probably happen.

#### Hardware info:
- RTX 3080 with 10GB dedicated VRAM.
- RX 5800x3d 
- 32GB RAM

#### Software versions:
- Latest NVIDIA drivers (537.13)
- Windows 11 (version 22H2, build 22621.2215)
- Sunshine nightly (`0.20.0.b00d7af36929f70cdb887dc0adba98b1110a503e`)
- HAGS enabled

#### Game settings:
- Jedi Survivor (patch 7)
- 4k, mostly epic settings (testing the limits)
- DLSS set to quality

**Comment by ReenigneArcher** [comment]
@noahtallen Nightly is sort of a secret... but links are here: https://app.lizardbyte.dev/Sunshine/

I'm slowly working on improvements to the nightly releases so they will be more obvious.

**Comment by noahtallen** [comment]
Thanks!
